services:
  backend:
    build: ./backend
    environment:
      APP_ENV: ${APP_ENV:-production}
    ports:
      - 8000:8000
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: unless-stopped
