/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminCompletionOut,
  AdminListCompletionsParams,
  AdminListQuestsParams,
  AdminQuestIn,
  AdminQuestOut,
  AdminQuestPatch,
  AdminReportOut,
  CompletionReview,
  ErrorResponse,
  HTTPValidationError,
  ReportResolution,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type adminListQuestsResponse200 = {
  data: AdminQuestOut[];
  status: 200;
};

export type adminListQuestsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminListQuestsResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminListQuestsResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminListQuestsResponseSuccess = adminListQuestsResponse200 & {
  headers: Headers;
};
export type adminListQuestsResponseError = (
  | adminListQuestsResponse401
  | adminListQuestsResponse403
  | adminListQuestsResponse422
) & {
  headers: Headers;
};

export type adminListQuestsResponse =
  adminListQuestsResponseSuccess | adminListQuestsResponseError;

export const getAdminListQuestsUrl = (params?: AdminListQuestsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/quests?${stringifiedParams}`
    : `/api/admin/quests`;
};

/**
 * All quests, newest first. Optionally filter by status.
 * @summary Admin List Quests
 */
export const adminListQuests = async (
  params?: AdminListQuestsParams,
  options?: RequestInit,
): Promise<adminListQuestsResponse> => {
  const res = await fetch(getAdminListQuestsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminListQuestsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminListQuestsResponse;
};

export const getAdminListQuestsQueryKey = (params?: AdminListQuestsParams) => {
  return [`/api/admin/quests`, ...(params ? [params] : [])] as const;
};

export const getAdminListQuestsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListQuests>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListQuestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListQuests>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminListQuestsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListQuests>>> = ({
    signal,
  }) => adminListQuests(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListQuests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListQuestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListQuests>>
>;
export type AdminListQuestsQueryError = ErrorResponse | HTTPValidationError;

export function useAdminListQuests<
  TData = Awaited<ReturnType<typeof adminListQuests>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: undefined | AdminListQuestsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListQuests>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListQuests>>,
          TError,
          Awaited<ReturnType<typeof adminListQuests>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListQuests<
  TData = Awaited<ReturnType<typeof adminListQuests>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListQuestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListQuests>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListQuests>>,
          TError,
          Awaited<ReturnType<typeof adminListQuests>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListQuests<
  TData = Awaited<ReturnType<typeof adminListQuests>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListQuestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListQuests>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Admin List Quests
 */

export function useAdminListQuests<
  TData = Awaited<ReturnType<typeof adminListQuests>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListQuestsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListQuests>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminListQuestsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type adminCreateQuestResponse201 = {
  data: AdminQuestOut;
  status: 201;
};

export type adminCreateQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminCreateQuestResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminCreateQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type adminCreateQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminCreateQuestResponseSuccess = adminCreateQuestResponse201 & {
  headers: Headers;
};
export type adminCreateQuestResponseError = (
  | adminCreateQuestResponse401
  | adminCreateQuestResponse403
  | adminCreateQuestResponse409
  | adminCreateQuestResponse422
) & {
  headers: Headers;
};

export type adminCreateQuestResponse =
  adminCreateQuestResponseSuccess | adminCreateQuestResponseError;

export const getAdminCreateQuestUrl = () => {
  return `/api/admin/quests`;
};

/**
 * Create a quest, as a draft by default. Creating it as `published`
 * fails with 409 if it isn't publishable yet.
 * @summary Admin Create Quest
 */
export const adminCreateQuest = async (
  adminQuestIn: AdminQuestIn,
  options?: RequestInit,
): Promise<adminCreateQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getAdminCreateQuestUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(adminQuestIn),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminCreateQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminCreateQuestResponse;
};

export const getAdminCreateQuestMutationKey = () =>
  ["adminCreateQuest"] as const;

export const getAdminCreateQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminCreateQuest>>,
    TError,
    AdminCreateQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminCreateQuest>>,
  TError,
  AdminCreateQuestMutationVariables,
  TContext
> => {
  const mutationKey = getAdminCreateQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminCreateQuest>>,
    AdminCreateQuestMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return adminCreateQuest(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminCreateQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminCreateQuest>>
>;
export type AdminCreateQuestMutationBody = AdminQuestIn;
export type AdminCreateQuestMutationError = ErrorResponse | HTTPValidationError;
export type AdminCreateQuestMutationVariables = { data: AdminQuestIn };

/**
 * @summary Admin Create Quest
 */
export const useAdminCreateQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminCreateQuest>>,
      TError,
      AdminCreateQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminCreateQuest>>,
  TError,
  AdminCreateQuestMutationVariables,
  TContext
> => {
  return useMutation(getAdminCreateQuestMutationOptions(options), queryClient);
};
export type adminGetQuestResponse200 = {
  data: AdminQuestOut;
  status: 200;
};

export type adminGetQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminGetQuestResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminGetQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type adminGetQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminGetQuestResponseSuccess = adminGetQuestResponse200 & {
  headers: Headers;
};
export type adminGetQuestResponseError = (
  | adminGetQuestResponse401
  | adminGetQuestResponse403
  | adminGetQuestResponse404
  | adminGetQuestResponse422
) & {
  headers: Headers;
};

export type adminGetQuestResponse =
  adminGetQuestResponseSuccess | adminGetQuestResponseError;

export const getAdminGetQuestUrl = (questId: string) => {
  return `/api/admin/quests/${questId}`;
};

/**
 * @summary Admin Get Quest
 */
export const adminGetQuest = async (
  questId: string,
  options?: RequestInit,
): Promise<adminGetQuestResponse> => {
  const res = await fetch(getAdminGetQuestUrl(questId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminGetQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminGetQuestResponse;
};

export const getAdminGetQuestQueryKey = (questId: string) => {
  return [`/api/admin/quests/${questId}`] as const;
};

export const getAdminGetQuestQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminGetQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetQuestQueryKey(questId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetQuest>>> = ({
    signal,
  }) => adminGetQuest(questId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: questId !== null && questId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetQuest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminGetQuestQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetQuest>>
>;
export type AdminGetQuestQueryError = ErrorResponse | HTTPValidationError;

export function useAdminGetQuest<
  TData = Awaited<ReturnType<typeof adminGetQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminGetQuest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetQuest>>,
          TError,
          Awaited<ReturnType<typeof adminGetQuest>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminGetQuest<
  TData = Awaited<ReturnType<typeof adminGetQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminGetQuest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetQuest>>,
          TError,
          Awaited<ReturnType<typeof adminGetQuest>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminGetQuest<
  TData = Awaited<ReturnType<typeof adminGetQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminGetQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Admin Get Quest
 */

export function useAdminGetQuest<
  TData = Awaited<ReturnType<typeof adminGetQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminGetQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminGetQuestQueryOptions(questId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type adminUpdateQuestResponse200 = {
  data: AdminQuestOut;
  status: 200;
};

export type adminUpdateQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminUpdateQuestResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminUpdateQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type adminUpdateQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type adminUpdateQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminUpdateQuestResponseSuccess = adminUpdateQuestResponse200 & {
  headers: Headers;
};
export type adminUpdateQuestResponseError = (
  | adminUpdateQuestResponse401
  | adminUpdateQuestResponse403
  | adminUpdateQuestResponse404
  | adminUpdateQuestResponse409
  | adminUpdateQuestResponse422
) & {
  headers: Headers;
};

export type adminUpdateQuestResponse =
  adminUpdateQuestResponseSuccess | adminUpdateQuestResponseError;

export const getAdminUpdateQuestUrl = (questId: string) => {
  return `/api/admin/quests/${questId}`;
};

/**
 * Change only the fields you send.
 *
 * `status` publishes, unpublishes (draft), or retires a quest. A published
 * quest must stay publishable.
 * @summary Admin Update Quest
 */
export const adminUpdateQuest = async (
  questId: string,
  adminQuestPatch: AdminQuestPatch,
  options?: RequestInit,
): Promise<adminUpdateQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getAdminUpdateQuestUrl(questId), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(adminQuestPatch),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminUpdateQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminUpdateQuestResponse;
};

export const getAdminUpdateQuestMutationKey = () =>
  ["adminUpdateQuest"] as const;

export const getAdminUpdateQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminUpdateQuest>>,
    TError,
    AdminUpdateQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminUpdateQuest>>,
  TError,
  AdminUpdateQuestMutationVariables,
  TContext
> => {
  const mutationKey = getAdminUpdateQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminUpdateQuest>>,
    AdminUpdateQuestMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return adminUpdateQuest(questId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUpdateQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminUpdateQuest>>
>;
export type AdminUpdateQuestMutationBody = AdminQuestPatch;
export type AdminUpdateQuestMutationError = ErrorResponse | HTTPValidationError;
export type AdminUpdateQuestMutationVariables = {
  questId: string;
  data: AdminQuestPatch;
};

/**
 * @summary Admin Update Quest
 */
export const useAdminUpdateQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminUpdateQuest>>,
      TError,
      AdminUpdateQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminUpdateQuest>>,
  TError,
  AdminUpdateQuestMutationVariables,
  TContext
> => {
  return useMutation(getAdminUpdateQuestMutationOptions(options), queryClient);
};
export type adminListCompletionsResponse200 = {
  data: AdminCompletionOut[];
  status: 200;
};

export type adminListCompletionsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminListCompletionsResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminListCompletionsResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminListCompletionsResponseSuccess =
  adminListCompletionsResponse200 & {
    headers: Headers;
  };
export type adminListCompletionsResponseError = (
  | adminListCompletionsResponse401
  | adminListCompletionsResponse403
  | adminListCompletionsResponse422
) & {
  headers: Headers;
};

export type adminListCompletionsResponse =
  adminListCompletionsResponseSuccess | adminListCompletionsResponseError;

export const getAdminListCompletionsUrl = (
  params?: AdminListCompletionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/completions?${stringifiedParams}`
    : `/api/admin/completions`;
};

/**
 * Completions waiting for review (or with another status), oldest first.
 * @summary Admin List Completions
 */
export const adminListCompletions = async (
  params?: AdminListCompletionsParams,
  options?: RequestInit,
): Promise<adminListCompletionsResponse> => {
  const res = await fetch(getAdminListCompletionsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminListCompletionsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminListCompletionsResponse;
};

export const getAdminListCompletionsQueryKey = (
  params?: AdminListCompletionsParams,
) => {
  return [`/api/admin/completions`, ...(params ? [params] : [])] as const;
};

export const getAdminListCompletionsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListCompletions>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListCompletionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListCompletions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminListCompletionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListCompletions>>
  > = ({ signal }) => adminListCompletions(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListCompletions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListCompletionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListCompletions>>
>;
export type AdminListCompletionsQueryError =
  ErrorResponse | HTTPValidationError;

export function useAdminListCompletions<
  TData = Awaited<ReturnType<typeof adminListCompletions>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: undefined | AdminListCompletionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListCompletions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListCompletions>>,
          TError,
          Awaited<ReturnType<typeof adminListCompletions>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListCompletions<
  TData = Awaited<ReturnType<typeof adminListCompletions>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListCompletionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListCompletions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListCompletions>>,
          TError,
          Awaited<ReturnType<typeof adminListCompletions>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListCompletions<
  TData = Awaited<ReturnType<typeof adminListCompletions>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListCompletionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListCompletions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Admin List Completions
 */

export function useAdminListCompletions<
  TData = Awaited<ReturnType<typeof adminListCompletions>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params?: AdminListCompletionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListCompletions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminListCompletionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type adminReviewCompletionResponse200 = {
  data: AdminCompletionOut;
  status: 200;
};

export type adminReviewCompletionResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminReviewCompletionResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminReviewCompletionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type adminReviewCompletionResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type adminReviewCompletionResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminReviewCompletionResponseSuccess =
  adminReviewCompletionResponse200 & {
    headers: Headers;
  };
export type adminReviewCompletionResponseError = (
  | adminReviewCompletionResponse401
  | adminReviewCompletionResponse403
  | adminReviewCompletionResponse404
  | adminReviewCompletionResponse409
  | adminReviewCompletionResponse422
) & {
  headers: Headers;
};

export type adminReviewCompletionResponse =
  adminReviewCompletionResponseSuccess | adminReviewCompletionResponseError;

export const getAdminReviewCompletionUrl = (completionId: string) => {
  return `/api/admin/completions/${completionId}/review`;
};

/**
 * Approve (awards the quest's points) or reject (with an explanation).
 *
 * Only pending completions can be reviewed, so repeated approvals can't
 * award points twice.
 * @summary Admin Review Completion
 */
export const adminReviewCompletion = async (
  completionId: string,
  completionReview: CompletionReview,
  options?: RequestInit,
): Promise<adminReviewCompletionResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getAdminReviewCompletionUrl(completionId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(completionReview),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminReviewCompletionResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminReviewCompletionResponse;
};

export const getAdminReviewCompletionMutationKey = () =>
  ["adminReviewCompletion"] as const;

export const getAdminReviewCompletionMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminReviewCompletion>>,
    TError,
    AdminReviewCompletionMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminReviewCompletion>>,
  TError,
  AdminReviewCompletionMutationVariables,
  TContext
> => {
  const mutationKey = getAdminReviewCompletionMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminReviewCompletion>>,
    AdminReviewCompletionMutationVariables
  > = (props) => {
    const { completionId, data } = props ?? {};

    return adminReviewCompletion(completionId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminReviewCompletionMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminReviewCompletion>>
>;
export type AdminReviewCompletionMutationBody = CompletionReview;
export type AdminReviewCompletionMutationError =
  ErrorResponse | HTTPValidationError;
export type AdminReviewCompletionMutationVariables = {
  completionId: string;
  data: CompletionReview;
};

/**
 * @summary Admin Review Completion
 */
export const useAdminReviewCompletion = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminReviewCompletion>>,
      TError,
      AdminReviewCompletionMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminReviewCompletion>>,
  TError,
  AdminReviewCompletionMutationVariables,
  TContext
> => {
  return useMutation(
    getAdminReviewCompletionMutationOptions(options),
    queryClient,
  );
};
export type adminListReportsResponse200 = {
  data: AdminReportOut[];
  status: 200;
};

export type adminListReportsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminListReportsResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminListReportsResponseSuccess = adminListReportsResponse200 & {
  headers: Headers;
};
export type adminListReportsResponseError = (
  adminListReportsResponse401 | adminListReportsResponse403
) & {
  headers: Headers;
};

export type adminListReportsResponse =
  adminListReportsResponseSuccess | adminListReportsResponseError;

export const getAdminListReportsUrl = () => {
  return `/api/admin/reports`;
};

/**
 * Open content reports, oldest first.
 * @summary Admin List Reports
 */
export const adminListReports = async (
  options?: RequestInit,
): Promise<adminListReportsResponse> => {
  const res = await fetch(getAdminListReportsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminListReportsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminListReportsResponse;
};

export const getAdminListReportsQueryKey = () => {
  return [`/api/admin/reports`] as const;
};

export const getAdminListReportsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListReports>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof adminListReports>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminListReportsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListReports>>
  > = ({ signal }) => adminListReports({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListReports>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListReportsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListReports>>
>;
export type AdminListReportsQueryError = ErrorResponse;

export function useAdminListReports<
  TData = Awaited<ReturnType<typeof adminListReports>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListReports>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListReports>>,
          TError,
          Awaited<ReturnType<typeof adminListReports>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListReports<
  TData = Awaited<ReturnType<typeof adminListReports>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListReports>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListReports>>,
          TError,
          Awaited<ReturnType<typeof adminListReports>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListReports<
  TData = Awaited<ReturnType<typeof adminListReports>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListReports>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Admin List Reports
 */

export function useAdminListReports<
  TData = Awaited<ReturnType<typeof adminListReports>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListReports>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminListReportsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type adminResolveReportResponse200 = {
  data: AdminQuestOut;
  status: 200;
};

export type adminResolveReportResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type adminResolveReportResponse403 = {
  data: ErrorResponse;
  status: 403;
};

export type adminResolveReportResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type adminResolveReportResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminResolveReportResponseSuccess =
  adminResolveReportResponse200 & {
    headers: Headers;
  };
export type adminResolveReportResponseError = (
  | adminResolveReportResponse401
  | adminResolveReportResponse403
  | adminResolveReportResponse404
  | adminResolveReportResponse422
) & {
  headers: Headers;
};

export type adminResolveReportResponse =
  adminResolveReportResponseSuccess | adminResolveReportResponseError;

export const getAdminResolveReportUrl = (reportId: string) => {
  return `/api/admin/reports/${reportId}/resolve`;
};

/**
 * Close a report. Retiring the quest also closes all its other reports.
 * @summary Admin Resolve Report
 */
export const adminResolveReport = async (
  reportId: string,
  reportResolution: ReportResolution,
  options?: RequestInit,
): Promise<adminResolveReportResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getAdminResolveReportUrl(reportId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(reportResolution),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminResolveReportResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminResolveReportResponse;
};

export const getAdminResolveReportMutationKey = () =>
  ["adminResolveReport"] as const;

export const getAdminResolveReportMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminResolveReport>>,
    TError,
    AdminResolveReportMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminResolveReport>>,
  TError,
  AdminResolveReportMutationVariables,
  TContext
> => {
  const mutationKey = getAdminResolveReportMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminResolveReport>>,
    AdminResolveReportMutationVariables
  > = (props) => {
    const { reportId, data } = props ?? {};

    return adminResolveReport(reportId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminResolveReportMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminResolveReport>>
>;
export type AdminResolveReportMutationBody = ReportResolution;
export type AdminResolveReportMutationError =
  ErrorResponse | HTTPValidationError;
export type AdminResolveReportMutationVariables = {
  reportId: string;
  data: ReportResolution;
};

/**
 * @summary Admin Resolve Report
 */
export const useAdminResolveReport = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminResolveReport>>,
      TError,
      AdminResolveReportMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminResolveReport>>,
  TError,
  AdminResolveReportMutationVariables,
  TContext
> => {
  return useMutation(
    getAdminResolveReportMutationOptions(options),
    queryClient,
  );
};
