/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  HTTPValidationError,
  Suggestions,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listSuggestionsResponse200 = {
  data: Suggestions;
  status: 200;
};

export type listSuggestionsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listSuggestionsResponseSuccess = listSuggestionsResponse200 & {
  headers: Headers;
};
export type listSuggestionsResponseError = listSuggestionsResponse401 & {
  headers: Headers;
};

export type listSuggestionsResponse =
  listSuggestionsResponseSuccess | listSuggestionsResponseError;

export const getListSuggestionsUrl = () => {
  return `/api/suggestions`;
};

/**
 * Discoverable players sharing at least one hobby, most shared first.
 * @summary List Suggestions
 */
export const listSuggestions = async (
  options?: RequestInit,
): Promise<listSuggestionsResponse> => {
  const res = await fetch(getListSuggestionsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSuggestionsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listSuggestionsResponse;
};

export const getListSuggestionsQueryKey = () => {
  return [`/api/suggestions`] as const;
};

export const getListSuggestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSuggestions>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listSuggestions>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListSuggestionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSuggestions>>> = ({
    signal,
  }) => listSuggestions({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSuggestions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSuggestionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSuggestions>>
>;
export type ListSuggestionsQueryError = ErrorResponse;

export function useListSuggestions<
  TData = Awaited<ReturnType<typeof listSuggestions>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSuggestions>>,
          TError,
          Awaited<ReturnType<typeof listSuggestions>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuggestions<
  TData = Awaited<ReturnType<typeof listSuggestions>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSuggestions>>,
          TError,
          Awaited<ReturnType<typeof listSuggestions>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSuggestions<
  TData = Awaited<ReturnType<typeof listSuggestions>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Suggestions
 */

export function useListSuggestions<
  TData = Awaited<ReturnType<typeof listSuggestions>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSuggestions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListSuggestionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type dismissSuggestionResponse204 = {
  data: void;
  status: 204;
};

export type dismissSuggestionResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type dismissSuggestionResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type dismissSuggestionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type dismissSuggestionResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type dismissSuggestionResponseSuccess = dismissSuggestionResponse204 & {
  headers: Headers;
};
export type dismissSuggestionResponseError = (
  | dismissSuggestionResponse400
  | dismissSuggestionResponse401
  | dismissSuggestionResponse404
  | dismissSuggestionResponse422
) & {
  headers: Headers;
};

export type dismissSuggestionResponse =
  dismissSuggestionResponseSuccess | dismissSuggestionResponseError;

export const getDismissSuggestionUrl = (playerId: number) => {
  return `/api/suggestions/${playerId}/dismiss`;
};

/**
 * Stop suggesting this player.
 * @summary Dismiss Suggestion
 */
export const dismissSuggestion = async (
  playerId: number,
  options?: RequestInit,
): Promise<dismissSuggestionResponse> => {
  const res = await fetch(getDismissSuggestionUrl(playerId), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dismissSuggestionResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as dismissSuggestionResponse;
};

export const getDismissSuggestionMutationKey = () =>
  ["dismissSuggestion"] as const;

export const getDismissSuggestionMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dismissSuggestion>>,
    TError,
    DismissSuggestionMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dismissSuggestion>>,
  TError,
  DismissSuggestionMutationVariables,
  TContext
> => {
  const mutationKey = getDismissSuggestionMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dismissSuggestion>>,
    DismissSuggestionMutationVariables
  > = (props) => {
    const { playerId } = props ?? {};

    return dismissSuggestion(playerId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DismissSuggestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof dismissSuggestion>>
>;

export type DismissSuggestionMutationError =
  ErrorResponse | HTTPValidationError;
export type DismissSuggestionMutationVariables = { playerId: number };

/**
 * @summary Dismiss Suggestion
 */
export const useDismissSuggestion = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dismissSuggestion>>,
      TError,
      DismissSuggestionMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dismissSuggestion>>,
  TError,
  DismissSuggestionMutationVariables,
  TContext
> => {
  return useMutation(getDismissSuggestionMutationOptions(options), queryClient);
};
