/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  LoginInfo,
  UserCreate,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type rootGetResponse200 = {
  data: unknown;
  status: 200;
};

export type rootGetResponseSuccess = rootGetResponse200 & {
  headers: Headers;
};
export type rootGetResponse = rootGetResponseSuccess;

export const getRootGetUrl = () => {
  return `/api/`;
};

/**
 * @summary Root
 */
export const rootGet = async (
  options?: RequestInit,
): Promise<rootGetResponse> => {
  const res = await fetch(getRootGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rootGetResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as rootGetResponse;
};

export const getRootGetQueryKey = () => {
  return [`/api/`] as const;
};

export const getRootGetQueryOptions = <
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRootGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({
    signal,
  }) => rootGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof rootGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof rootGet>>
>;
export type RootGetQueryError = unknown;

export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Root
 */

export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRootGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type currentUserCurrentUserGetResponse200 = {
  data: LoginInfo;
  status: 200;
};

export type currentUserCurrentUserGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type currentUserCurrentUserGetResponseSuccess =
  currentUserCurrentUserGetResponse200 & {
    headers: Headers;
  };
export type currentUserCurrentUserGetResponseError =
  currentUserCurrentUserGetResponse422 & {
    headers: Headers;
  };

export type currentUserCurrentUserGetResponse =
  | currentUserCurrentUserGetResponseSuccess
  | currentUserCurrentUserGetResponseError;

export const getCurrentUserCurrentUserGetUrl = () => {
  return `/api/current_user`;
};

/**
 * @summary Current User
 */
export const currentUserCurrentUserGet = async (
  options?: RequestInit,
): Promise<currentUserCurrentUserGetResponse> => {
  const res = await fetch(getCurrentUserCurrentUserGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: currentUserCurrentUserGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as currentUserCurrentUserGetResponse;
};

export const getCurrentUserCurrentUserGetQueryKey = () => {
  return [`/api/current_user`] as const;
};

export const getCurrentUserCurrentUserGetQueryOptions = <
  TData = Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
  TError = HTTPValidationError,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCurrentUserCurrentUserGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof currentUserCurrentUserGet>>
  > = ({ signal }) => currentUserCurrentUserGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CurrentUserCurrentUserGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof currentUserCurrentUserGet>>
>;
export type CurrentUserCurrentUserGetQueryError = HTTPValidationError;

export function useCurrentUserCurrentUserGet<
  TData = Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
  TError = HTTPValidationError,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
          TError,
          Awaited<ReturnType<typeof currentUserCurrentUserGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCurrentUserCurrentUserGet<
  TData = Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
          TError,
          Awaited<ReturnType<typeof currentUserCurrentUserGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCurrentUserCurrentUserGet<
  TData = Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Current User
 */

export function useCurrentUserCurrentUserGet<
  TData = Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof currentUserCurrentUserGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCurrentUserCurrentUserGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getUsersUsersGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getUsersUsersGetResponseSuccess = getUsersUsersGetResponse200 & {
  headers: Headers;
};
export type getUsersUsersGetResponse = getUsersUsersGetResponseSuccess;

export const getGetUsersUsersGetUrl = () => {
  return `/api/users`;
};

/**
 * Return all saved users.
 * @summary Get Users
 */
export const getUsersUsersGet = async (
  options?: RequestInit,
): Promise<getUsersUsersGetResponse> => {
  const res = await fetch(getGetUsersUsersGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersUsersGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUsersUsersGetResponse;
};

export const getGetUsersUsersGetQueryKey = () => {
  return [`/api/users`] as const;
};

export const getGetUsersUsersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersUsersGet>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersUsersGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUsersUsersGet>>
  > = ({ signal }) => getUsersUsersGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersUsersGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersUsersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUsersGet>>
>;
export type GetUsersUsersGetQueryError = unknown;

export function useGetUsersUsersGet<
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersUsersGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof getUsersUsersGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersUsersGet<
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersUsersGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof getUsersUsersGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersUsersGet<
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersUsersGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Users
 */

export function useGetUsersUsersGet<
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersUsersGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersUsersGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type addUserUsersPostResponse201 = {
  data: unknown;
  status: 201;
};

export type addUserUsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type addUserUsersPostResponseSuccess = addUserUsersPostResponse201 & {
  headers: Headers;
};
export type addUserUsersPostResponseError = addUserUsersPostResponse422 & {
  headers: Headers;
};

export type addUserUsersPostResponse =
  addUserUsersPostResponseSuccess | addUserUsersPostResponseError;

export const getAddUserUsersPostUrl = () => {
  return `/api/users`;
};

/**
 * Persist a new user name.
 * @summary Add User
 */
export const addUserUsersPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<addUserUsersPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getAddUserUsersPostUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(userCreate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: addUserUsersPostResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as addUserUsersPostResponse;
};

export const getAddUserUsersPostMutationKey = () =>
  ["addUserUsersPost"] as const;

export const getAddUserUsersPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addUserUsersPost>>,
    TError,
    AddUserUsersPostMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addUserUsersPost>>,
  TError,
  AddUserUsersPostMutationVariables,
  TContext
> => {
  const mutationKey = getAddUserUsersPostMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addUserUsersPost>>,
    AddUserUsersPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return addUserUsersPost(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddUserUsersPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof addUserUsersPost>>
>;
export type AddUserUsersPostMutationBody = UserCreate;
export type AddUserUsersPostMutationError = HTTPValidationError;
export type AddUserUsersPostMutationVariables = { data: UserCreate };

/**
 * @summary Add User
 */
export const useAddUserUsersPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addUserUsersPost>>,
      TError,
      AddUserUsersPostMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addUserUsersPost>>,
  TError,
  AddUserUsersPostMutationVariables,
  TContext
> => {
  return useMutation(getAddUserUsersPostMutationOptions(options), queryClient);
};
