/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { HTTPValidationError, UserCreate } from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type rootGetResponse200 = {
  data: unknown;
  status: 200;
};

export type rootGetResponseSuccess = rootGetResponse200 & {
  headers: Headers;
};
export type rootGetResponse = rootGetResponseSuccess;

export const getRootGetUrl = () => {
  return `http://localhost:8000/`;
};

/**
 * @summary Root
 */
export const rootGet = async (
  options?: RequestInit,
): Promise<rootGetResponse> => {
  const res = await fetch(getRootGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rootGetResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as rootGetResponse;
};

export const getRootGetQueryKey = () => {
  return [`http://localhost:8000/`] as const;
};

export const getRootGetQueryOptions = <
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRootGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({
    signal,
  }) => rootGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof rootGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RootGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof rootGet>>
>;
export type RootGetQueryError = unknown;

/**
 * @summary Root
 */

export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRootGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getUsersUsersGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getUsersUsersGetResponseSuccess = getUsersUsersGetResponse200 & {
  headers: Headers;
};
export type getUsersUsersGetResponse = getUsersUsersGetResponseSuccess;

export const getGetUsersUsersGetUrl = () => {
  return `http://localhost:8000/users`;
};

/**
 * Gibt alle gespeicherten Benutzer zurück.
 * @summary Get Users
 */
export const getUsersUsersGet = async (
  options?: RequestInit,
): Promise<getUsersUsersGetResponse> => {
  const res = await fetch(getGetUsersUsersGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersUsersGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUsersUsersGetResponse;
};

export const getGetUsersUsersGetQueryKey = () => {
  return [`http://localhost:8000/users`] as const;
};

export const getGetUsersUsersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUsersUsersGet>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersUsersGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUsersUsersGet>>
  > = ({ signal }) => getUsersUsersGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersUsersGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUsersUsersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUsersGet>>
>;
export type GetUsersUsersGetQueryError = unknown;

/**
 * @summary Get Users
 */

export function useGetUsersUsersGet<
  TData = Awaited<ReturnType<typeof getUsersUsersGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUsersUsersGet>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUsersUsersGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type addUserUsersPostResponse201 = {
  data: unknown;
  status: 201;
};

export type addUserUsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type addUserUsersPostResponseSuccess = addUserUsersPostResponse201 & {
  headers: Headers;
};
export type addUserUsersPostResponseError = addUserUsersPostResponse422 & {
  headers: Headers;
};

export type addUserUsersPostResponse =
  addUserUsersPostResponseSuccess | addUserUsersPostResponseError;

export const getAddUserUsersPostUrl = () => {
  return `http://localhost:8000/users`;
};

/**
 * Speichert einen neuen Benutzernamen.
 * @summary Add User
 */
export const addUserUsersPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<addUserUsersPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getAddUserUsersPostUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(userCreate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: addUserUsersPostResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as addUserUsersPostResponse;
};

export const getAddUserUsersPostMutationKey = () =>
  ["addUserUsersPost"] as const;

export const getAddUserUsersPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addUserUsersPost>>,
    TError,
    AddUserUsersPostMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addUserUsersPost>>,
  TError,
  AddUserUsersPostMutationVariables,
  TContext
> => {
  const mutationKey = getAddUserUsersPostMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addUserUsersPost>>,
    AddUserUsersPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return addUserUsersPost(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddUserUsersPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof addUserUsersPost>>
>;
export type AddUserUsersPostMutationBody = UserCreate;
export type AddUserUsersPostMutationError = HTTPValidationError;
export type AddUserUsersPostMutationVariables = { data: UserCreate };

/**
 * @summary Add User
 */
export const useAddUserUsersPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addUserUsersPost>>,
    TError,
    AddUserUsersPostMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationResult<
  Awaited<ReturnType<typeof addUserUsersPost>>,
  TError,
  AddUserUsersPostMutationVariables,
  TContext
> => {
  return useMutation(getAddUserUsersPostMutationOptions(options));
};
