/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  Friends,
  HTTPValidationError,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listFriendsResponse200 = {
  data: Friends;
  status: 200;
};

export type listFriendsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listFriendsResponseSuccess = listFriendsResponse200 & {
  headers: Headers;
};
export type listFriendsResponseError = listFriendsResponse401 & {
  headers: Headers;
};

export type listFriendsResponse =
  listFriendsResponseSuccess | listFriendsResponseError;

export const getListFriendsUrl = () => {
  return `/api/friends`;
};

/**
 * My friends plus open incoming and outgoing requests.
 * @summary List Friends
 */
export const listFriends = async (
  options?: RequestInit,
): Promise<listFriendsResponse> => {
  const res = await fetch(getListFriendsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listFriendsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listFriendsResponse;
};

export const getListFriendsQueryKey = () => {
  return [`/api/friends`] as const;
};

export const getListFriendsQueryOptions = <
  TData = Awaited<ReturnType<typeof listFriends>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listFriends>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListFriendsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listFriends>>> = ({
    signal,
  }) => listFriends({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listFriends>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListFriendsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFriends>>
>;
export type ListFriendsQueryError = ErrorResponse;

export function useListFriends<
  TData = Awaited<ReturnType<typeof listFriends>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listFriends>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFriends>>,
          TError,
          Awaited<ReturnType<typeof listFriends>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListFriends<
  TData = Awaited<ReturnType<typeof listFriends>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listFriends>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFriends>>,
          TError,
          Awaited<ReturnType<typeof listFriends>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListFriends<
  TData = Awaited<ReturnType<typeof listFriends>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listFriends>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Friends
 */

export function useListFriends<
  TData = Awaited<ReturnType<typeof listFriends>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listFriends>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListFriendsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type sendFriendRequestResponse201 = {
  data: Friends;
  status: 201;
};

export type sendFriendRequestResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type sendFriendRequestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type sendFriendRequestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type sendFriendRequestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type sendFriendRequestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type sendFriendRequestResponseSuccess = sendFriendRequestResponse201 & {
  headers: Headers;
};
export type sendFriendRequestResponseError = (
  | sendFriendRequestResponse400
  | sendFriendRequestResponse401
  | sendFriendRequestResponse404
  | sendFriendRequestResponse409
  | sendFriendRequestResponse422
) & {
  headers: Headers;
};

export type sendFriendRequestResponse =
  sendFriendRequestResponseSuccess | sendFriendRequestResponseError;

export const getSendFriendRequestUrl = (username: string) => {
  return `/api/friends/${username}`;
};

/**
 * Ask a discoverable player to be friends. They see it under incoming
 * requests and can accept or decline.
 * @summary Send Friend Request
 */
export const sendFriendRequest = async (
  username: string,
  options?: RequestInit,
): Promise<sendFriendRequestResponse> => {
  const res = await fetch(getSendFriendRequestUrl(username), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: sendFriendRequestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as sendFriendRequestResponse;
};

export const getSendFriendRequestMutationKey = () =>
  ["sendFriendRequest"] as const;

export const getSendFriendRequestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendFriendRequest>>,
    TError,
    SendFriendRequestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendFriendRequest>>,
  TError,
  SendFriendRequestMutationVariables,
  TContext
> => {
  const mutationKey = getSendFriendRequestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendFriendRequest>>,
    SendFriendRequestMutationVariables
  > = (props) => {
    const { username } = props ?? {};

    return sendFriendRequest(username, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendFriendRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendFriendRequest>>
>;

export type SendFriendRequestMutationError =
  ErrorResponse | HTTPValidationError;
export type SendFriendRequestMutationVariables = { username: string };

/**
 * @summary Send Friend Request
 */
export const useSendFriendRequest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sendFriendRequest>>,
      TError,
      SendFriendRequestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sendFriendRequest>>,
  TError,
  SendFriendRequestMutationVariables,
  TContext
> => {
  return useMutation(getSendFriendRequestMutationOptions(options), queryClient);
};
export type removeFriendResponse200 = {
  data: Friends;
  status: 200;
};

export type removeFriendResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type removeFriendResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type removeFriendResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type removeFriendResponseSuccess = removeFriendResponse200 & {
  headers: Headers;
};
export type removeFriendResponseError = (
  removeFriendResponse401 | removeFriendResponse404 | removeFriendResponse422
) & {
  headers: Headers;
};

export type removeFriendResponse =
  removeFriendResponseSuccess | removeFriendResponseError;

export const getRemoveFriendUrl = (username: string) => {
  return `/api/friends/${username}`;
};

/**
 * Decline their request, cancel mine, or remove a friend: whichever
 * relation exists with this player is removed for both of us.
 * @summary Remove Friend
 */
export const removeFriend = async (
  username: string,
  options?: RequestInit,
): Promise<removeFriendResponse> => {
  const res = await fetch(getRemoveFriendUrl(username), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeFriendResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as removeFriendResponse;
};

export const getRemoveFriendMutationKey = () => ["removeFriend"] as const;

export const getRemoveFriendMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFriend>>,
    TError,
    RemoveFriendMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFriend>>,
  TError,
  RemoveFriendMutationVariables,
  TContext
> => {
  const mutationKey = getRemoveFriendMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFriend>>,
    RemoveFriendMutationVariables
  > = (props) => {
    const { username } = props ?? {};

    return removeFriend(username, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFriendMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFriend>>
>;

export type RemoveFriendMutationError = ErrorResponse | HTTPValidationError;
export type RemoveFriendMutationVariables = { username: string };

/**
 * @summary Remove Friend
 */
export const useRemoveFriend = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeFriend>>,
      TError,
      RemoveFriendMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeFriend>>,
  TError,
  RemoveFriendMutationVariables,
  TContext
> => {
  return useMutation(getRemoveFriendMutationOptions(options), queryClient);
};
export type acceptFriendRequestResponse200 = {
  data: Friends;
  status: 200;
};

export type acceptFriendRequestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type acceptFriendRequestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type acceptFriendRequestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type acceptFriendRequestResponseSuccess =
  acceptFriendRequestResponse200 & {
    headers: Headers;
  };
export type acceptFriendRequestResponseError = (
  | acceptFriendRequestResponse401
  | acceptFriendRequestResponse404
  | acceptFriendRequestResponse422
) & {
  headers: Headers;
};

export type acceptFriendRequestResponse =
  acceptFriendRequestResponseSuccess | acceptFriendRequestResponseError;

export const getAcceptFriendRequestUrl = (username: string) => {
  return `/api/friends/${username}/accept`;
};

/**
 * Accept a request this player sent me; we become friends.
 * @summary Accept Friend Request
 */
export const acceptFriendRequest = async (
  username: string,
  options?: RequestInit,
): Promise<acceptFriendRequestResponse> => {
  const res = await fetch(getAcceptFriendRequestUrl(username), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: acceptFriendRequestResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as acceptFriendRequestResponse;
};

export const getAcceptFriendRequestMutationKey = () =>
  ["acceptFriendRequest"] as const;

export const getAcceptFriendRequestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptFriendRequest>>,
    TError,
    AcceptFriendRequestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptFriendRequest>>,
  TError,
  AcceptFriendRequestMutationVariables,
  TContext
> => {
  const mutationKey = getAcceptFriendRequestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptFriendRequest>>,
    AcceptFriendRequestMutationVariables
  > = (props) => {
    const { username } = props ?? {};

    return acceptFriendRequest(username, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptFriendRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptFriendRequest>>
>;

export type AcceptFriendRequestMutationError =
  ErrorResponse | HTTPValidationError;
export type AcceptFriendRequestMutationVariables = { username: string };

/**
 * @summary Accept Friend Request
 */
export const useAcceptFriendRequest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptFriendRequest>>,
      TError,
      AcceptFriendRequestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptFriendRequest>>,
  TError,
  AcceptFriendRequestMutationVariables,
  TContext
> => {
  return useMutation(
    getAcceptFriendRequestMutationOptions(options),
    queryClient,
  );
};
