/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
export type AdminCompletionOutStatus =
  (typeof AdminCompletionOutStatus)[keyof typeof AdminCompletionOutStatus];

export const AdminCompletionOutStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;

export interface AdminCompletionOut {
  id: number;
  quest_id: number;
  quest_title: string;
  player_name: string;
  note?: string | null;
  status: AdminCompletionOutStatus;
  completed_at: string;
  review_note?: string | null;
}

export type AdminQuestInKind =
  (typeof AdminQuestInKind)[keyof typeof AdminQuestInKind];

export const AdminQuestInKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export interface StepIn {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /** @maxLength 2000 */
  description?: string;
}

export interface QuizQuestionIn {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  /**
   * @minItems 2
   * @maxItems 8
   */
  choices: string[];
  /** @minimum 0 */
  correct_index: number;
}

export interface AdminQuestIn {
  /**
   * @minLength 1
   * @maxLength 120
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  description: string;
  location?: string | null;
  /**
   * @minimum 0
   * @maximum 1000
   */
  points: number;
  kind?: AdminQuestInKind;
  requires_approval?: boolean;
  latitude?: number | null;
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  cancelled?: boolean;
  /** @maxItems 20 */
  steps?: StepIn[];
  /** @maxItems 20 */
  questions?: QuizQuestionIn[];
}

export type AdminQuestOutKind =
  (typeof AdminQuestOutKind)[keyof typeof AdminQuestOutKind];

export const AdminQuestOutKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type AdminQuestOutStatus =
  (typeof AdminQuestOutStatus)[keyof typeof AdminQuestOutStatus];

export const AdminQuestOutStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface AdminQuizQuestionOut {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  /**
   * @minItems 2
   * @maxItems 8
   */
  choices: string[];
  /** @minimum 0 */
  correct_index: number;
  id: number;
}

export interface AdminQuestOut {
  id: number;
  title: string;
  description: string;
  location?: string | null;
  points: number;
  kind: AdminQuestOutKind;
  status: AdminQuestOutStatus;
  requires_approval: boolean;
  latitude?: number | null;
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  cancelled: boolean;
  author_name?: string | null;
  review_note?: string | null;
  steps: StepIn[];
  questions: AdminQuizQuestionOut[];
  completion_count: number;
  open_reports: number;
  /** Why the quest can't be published yet (empty if it can) */
  publish_problems: string[];
}

export type AdminReportOutQuestStatus =
  (typeof AdminReportOutQuestStatus)[keyof typeof AdminReportOutQuestStatus];

export const AdminReportOutQuestStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface AdminReportOut {
  id: number;
  quest_id: number;
  quest_title: string;
  quest_status: AdminReportOutQuestStatus;
  reporter_name: string;
  reason: string;
  created_at: string;
}

export interface Badge {
  key: string;
  title: string;
  description: string;
  earned: boolean;
  earned_at?: string | null;
  /** Progress towards the badge, capped at target */
  progress: number;
  /** Progress needed, e.g. 5 quests or 100 points */
  target: number;
}

export interface CompleteRequest {
  /** What the player did (shown to reviewers on approval quests) */
  note?: string | null;
}

export type CompletionResultStatus =
  (typeof CompletionResultStatus)[keyof typeof CompletionResultStatus];

export const CompletionResultStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;

export interface CompletionResult {
  quest_id: number;
  /** True once the completion is approved */
  completed: boolean;
  status: CompletionResultStatus;
  /** True if the quest was completed/submitted before this request */
  already_completed: boolean;
  /** Points granted by this request (0 if already completed or pending) */
  points_awarded: number;
  /** Player's updated total */
  total_points: number;
  completed_at: string;
}

export interface CompletionReview {
  approve: boolean;
  note?: string | null;
}

export interface ErrorResponse {
  detail: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HobbyOption {
  key: string;
  label: string;
}

export interface LeaderboardEntry {
  /** Players with equal points share a rank */
  rank: number;
  player_id: number;
  display_name: string;
  points: number;
  is_current_player: boolean;
}

export interface Leaderboard {
  /** Players with at least one point, best first */
  entries: LeaderboardEntry[];
  current_player: LeaderboardEntry;
}

export type PairSessionOutState =
  (typeof PairSessionOutState)[keyof typeof PairSessionOutState];

export const PairSessionOutState = {
  waiting: "waiting",
  completed: "completed",
  expired: "expired",
  cancelled: "cancelled",
} as const;

export interface PairSessionOut {
  code: string;
  quest_id: number;
  quest_title: string;
  host_name: string;
  partner_name?: string | null;
  is_host: boolean;
  state: PairSessionOutState;
  expires_at: string;
  /** Player the host invited, if any */
  invited_name?: string | null;
}

export interface PairJoinResult {
  session: PairSessionOut;
  completion: CompletionResult;
}

export interface PairStartRequest {
  /** Invite a suggested player: the code appears on their home screen */
  invite_player_id?: number | null;
}

export interface Player {
  /** Internal player ID */
  id: number;
  display_name: string;
  total_points: number;
  is_maintainer: boolean;
  /** Hobby keys, see GET /hobbies */
  hobbies: string[];
  /** Opted in to connection suggestions */
  discoverable: boolean;
}

export interface PlayerSearchResult {
  player_id: number;
  display_name: string;
}

export interface ProfileUpdate {
  /** @maxItems 20 */
  hobbies: string[];
  discoverable: boolean;
}

export type QuestOutKind = (typeof QuestOutKind)[keyof typeof QuestOutKind];

export const QuestOutKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type QuestOutStatus =
  (typeof QuestOutStatus)[keyof typeof QuestOutStatus];

export const QuestOutStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export type QuestOutMeetupState =
  (typeof QuestOutMeetupState)[keyof typeof QuestOutMeetupState] | null;

export const QuestOutMeetupState = {
  upcoming: "upcoming",
  live: "live",
  past: "past",
  cancelled: "cancelled",
} as const;

export type QuestOutCompletionStatus =
  | (typeof QuestOutCompletionStatus)[keyof typeof QuestOutCompletionStatus]
  | null;

export const QuestOutCompletionStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;

export interface StepOut {
  id: number;
  position: number;
  title: string;
  description: string;
  done: boolean;
}

export interface QuizQuestionOut {
  id: number;
  position: number;
  prompt: string;
  choices: string[];
}

export interface QuestOut {
  id: number;
  title: string;
  /** Instructions for the activity */
  description: string;
  location?: string | null;
  /** Reward for completing the quest */
  points: number;
  kind: QuestOutKind;
  status: QuestOutStatus;
  requires_approval: boolean;
  /** Map pin (WGS84) */
  latitude?: number | null;
  /** Map pin (WGS84) */
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  meetup_state?: QuestOutMeetupState;
  /** Set for player-submitted quests */
  author_name?: string | null;
  /** Current player has an approved completion */
  completed: boolean;
  /** UTC time of the current player's completion */
  completed_at?: string | null;
  completion_status?: QuestOutCompletionStatus;
  /** Maintainer's note on a rejected completion */
  review_note?: string | null;
  steps?: StepOut[];
  questions?: QuizQuestionOut[];
  rsvp?: boolean;
  rsvp_count?: number;
  reported?: boolean;
}

export interface QuestSubmission {
  /**
   * @minLength 3
   * @maxLength 120
   */
  title: string;
  /**
   * @minLength 10
   * @maxLength 2000
   */
  description: string;
  location?: string | null;
}

export interface QuizResult {
  passed: boolean;
  correct_count: number;
  total: number;
  /** Per question, whether the answer was right */
  correct: boolean[];
  completion?: CompletionResult | null;
}

export interface QuizSubmission {
  /** Chosen choice index per question, in order */
  answers: number[];
}

export interface ReportRequest {
  /**
   * @minLength 5
   * @maxLength 500
   */
  reason: string;
}

export interface ReportResolution {
  /** Also retire the reported quest */
  retire_quest: boolean;
}

export interface RsvpResult {
  rsvp: boolean;
  rsvp_count: number;
}

export type StatusChangeStatus =
  (typeof StatusChangeStatus)[keyof typeof StatusChangeStatus];

export const StatusChangeStatus = {
  draft: "draft",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface StatusChange {
  status: StatusChangeStatus;
  /** Shown to the author on rejection */
  note?: string | null;
}

export interface StepResult {
  step_id: number;
  steps_done: number;
  steps_total: number;
  /** Set when this step finished the quest */
  completion?: CompletionResult | null;
}

export type SubmissionOutStatus =
  (typeof SubmissionOutStatus)[keyof typeof SubmissionOutStatus];

export const SubmissionOutStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface SubmissionOut {
  id: number;
  title: string;
  description: string;
  location?: string | null;
  status: SubmissionOutStatus;
  review_note?: string | null;
}

export interface Suggestion {
  player_id: number;
  display_name: string;
  /** Labels of hobbies you share */
  shared_hobbies: string[];
}

export interface Suggestions {
  /** False until the player opts in */
  enabled: boolean;
  suggestions: Suggestion[];
}

export type SearchPlayersParams = {
  /**
   * Part of a display name
   * @minLength 2
   * @maxLength 100
   */
  q: string;
};

export type AdminListQuestsParams = {
  status_filter?: string | null;
};

export type AdminListCompletionsParams = {
  status_filter?: string;
};
