/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
export type AdminCompletionOutStatus =
  (typeof AdminCompletionOutStatus)[keyof typeof AdminCompletionOutStatus];

export const AdminCompletionOutStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;

export interface AdminCompletionOut {
  id: string;
  quest_id: string;
  quest_title: string;
  player_name: string;
  note?: string | null;
  status: AdminCompletionOutStatus;
  completed_at: string;
  review_note?: string | null;
}

export type AdminQuestInKind =
  (typeof AdminQuestInKind)[keyof typeof AdminQuestInKind];

export const AdminQuestInKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type AdminQuestInStatus =
  (typeof AdminQuestInStatus)[keyof typeof AdminQuestInStatus];

export const AdminQuestInStatus = {
  draft: "draft",
  published: "published",
} as const;

export interface StepIn {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /** @maxLength 2000 */
  description?: string;
}

export interface QuizQuestionIn {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  /**
   * @minItems 2
   * @maxItems 8
   */
  choices: string[];
  /** @minimum 0 */
  correct_index: number;
}

export interface AdminQuestIn {
  /**
   * @minLength 2
   * @maxLength 120
   */
  title: string;
  /** @maxLength 2000 */
  description?: string;
  location?: string | null;
  /**
   * @minimum 0
   * @maximum 1000
   */
  points: number;
  kind?: AdminQuestInKind;
  requires_approval?: boolean;
  requires_code?: boolean;
  requires_password?: boolean;
  password?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  cancelled?: boolean;
  /** @maxItems 20 */
  steps?: StepIn[];
  /** @maxItems 20 */
  questions?: QuizQuestionIn[];
  status?: AdminQuestInStatus;
}

export type AdminQuestOutKind =
  (typeof AdminQuestOutKind)[keyof typeof AdminQuestOutKind];

export const AdminQuestOutKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type AdminQuestOutStatus =
  (typeof AdminQuestOutStatus)[keyof typeof AdminQuestOutStatus];

export const AdminQuestOutStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface AdminQuizQuestionOut {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  prompt: string;
  /**
   * @minItems 2
   * @maxItems 8
   */
  choices: string[];
  /** @minimum 0 */
  correct_index: number;
  id: string;
}

export interface AdminQuestOut {
  id: string;
  title: string;
  description: string;
  location?: string | null;
  points: number;
  kind: AdminQuestOutKind;
  status: AdminQuestOutStatus;
  requires_approval: boolean;
  requires_code: boolean;
  requires_password: boolean;
  /** Stable code for the printable QR; maintainers only */
  verification_code: string | null;
  latitude?: number | null;
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  cancelled: boolean;
  author_name?: string | null;
  review_note?: string | null;
  steps: StepIn[];
  questions: AdminQuizQuestionOut[];
  completion_count: number;
  open_reports: number;
  /** Why the quest can't be published yet (empty if it can) */
  publish_problems: string[];
}

export type AdminQuestPatchKind =
  (typeof AdminQuestPatchKind)[keyof typeof AdminQuestPatchKind] | null;

export const AdminQuestPatchKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type AdminQuestPatchStatus =
  (typeof AdminQuestPatchStatus)[keyof typeof AdminQuestPatchStatus] | null;

export const AdminQuestPatchStatus = {
  draft: "draft",
  published: "published",
  retired: "retired",
} as const;

/**
 * Change only the fields you send (status changes publish or retire).
 */
export interface AdminQuestPatch {
  title?: string | null;
  description?: string | null;
  location?: string | null;
  points?: number | null;
  kind?: AdminQuestPatchKind;
  requires_approval?: boolean | null;
  requires_code?: boolean | null;
  requires_password?: boolean | null;
  password?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  cancelled?: boolean | null;
  steps?: StepIn[] | null;
  questions?: QuizQuestionIn[] | null;
  status?: AdminQuestPatchStatus;
}

export type AdminReportOutQuestStatus =
  (typeof AdminReportOutQuestStatus)[keyof typeof AdminReportOutQuestStatus];

export const AdminReportOutQuestStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface AdminReportOut {
  id: string;
  quest_id: string;
  quest_title: string;
  quest_status: AdminReportOutQuestStatus;
  reporter_name: string;
  reason: string;
  created_at: string;
}

export interface Badge {
  key: string;
  title: string;
  description: string;
  earned: boolean;
  earned_at?: string | null;
  /** Progress towards the badge, capped at target */
  progress: number;
  /** Progress needed, e.g. 5 quests or 100 points */
  target: number;
}

/**
 * Complete a solo quest or check in at a live meetup.
 */
export interface CompleteAction {
  type: "complete";
  /** What the player did (shown to reviewers on approval quests) */
  note?: string | null;
}

export type CompletionResultStatus =
  (typeof CompletionResultStatus)[keyof typeof CompletionResultStatus];

export const CompletionResultStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;

export interface CompletionResult {
  quest_id: string;
  /** True once the completion is approved */
  completed: boolean;
  status: CompletionResultStatus;
  /** True if the quest was completed/submitted before this request */
  already_completed: boolean;
  /** Points granted by this request (0 if already completed or pending) */
  points_awarded: number;
  /** Player's updated total */
  total_points: number;
  completed_at: string;
}

export interface CompletionReview {
  approve: boolean;
  note?: string | null;
}

export type CreatedQuestOutKind =
  (typeof CreatedQuestOutKind)[keyof typeof CreatedQuestOutKind];

export const CreatedQuestOutKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type CreatedQuestOutStatus =
  (typeof CreatedQuestOutStatus)[keyof typeof CreatedQuestOutStatus];

export const CreatedQuestOutStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export interface CreatedQuestOut {
  id: string;
  title: string;
  kind: CreatedQuestOutKind;
  status: CreatedQuestOutStatus;
}

export interface ErrorResponse {
  detail: string;
}

export interface FriendOut {
  username: string;
  display_name: string;
  total_points: number;
  /** When the request was accepted */
  since: string;
}

export interface FriendRequestOut {
  username: string;
  display_name: string;
  created_at: string;
}

export interface Friends {
  /** Accepted friends, most points first */
  friends: FriendOut[];
  /** Requests waiting for my answer, newest first */
  incoming: FriendRequestOut[];
  /** Requests I sent that are still open, newest first */
  outgoing: FriendRequestOut[];
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Health {
  message: string;
}

export interface HobbyOption {
  key: string;
  label: string;
}

export type LeaderboardScope =
  (typeof LeaderboardScope)[keyof typeof LeaderboardScope];

export const LeaderboardScope = {
  global: "global",
  friends: "friends",
} as const;

/**
 * Join a quest; needed before a first attempt at it (meetups use rsvp).
 */
export const JoinActionValue = {
  type: "join",
} as const;
export type JoinAction = typeof JoinActionValue;

export interface LeaderboardEntry {
  /** Players with equal points share a rank */
  rank: number;
  /** Username when the viewer may view this profile */
  username?: string | null;
  display_name: string;
  points: number;
  is_current_player: boolean;
}

export interface Leaderboard {
  scope: LeaderboardScope;
  /** Ranked best first. Global: everyone with at least one point (top 50). Friends: you and all your accepted friends. */
  entries: LeaderboardEntry[];
  current_player: LeaderboardEntry;
  /** Accepted friends of the current player (0 means the Friends view is empty) */
  friend_count: number;
}

export const LeaveActionValue = {
  type: "leave",
} as const;
export type LeaveAction = typeof LeaveActionValue;

export interface Suggestion {
  username: string;
  display_name: string;
  /** Labels of hobbies you share */
  shared_hobbies: string[];
}

export interface Suggestions {
  /** False until the player opts in */
  enabled: boolean;
  suggestions: Suggestion[];
}

export type PairSessionOutState =
  (typeof PairSessionOutState)[keyof typeof PairSessionOutState];

export const PairSessionOutState = {
  waiting: "waiting",
  completed: "completed",
  expired: "expired",
  cancelled: "cancelled",
} as const;

export interface PairSessionOut {
  code: string;
  quest_id: string;
  quest_title: string;
  host_name: string;
  partner_name?: string | null;
  is_host: boolean;
  state: PairSessionOutState;
  expires_at: string;
  /** Player the host invited, if any */
  invited_name?: string | null;
}

export interface Me {
  username: string;
  display_name: string;
  total_points: number;
  is_maintainer: boolean;
  /** Chosen hobby keys, see hobby_options */
  hobbies: string[];
  /** Opted in to connection suggestions */
  discoverable: boolean;
  badges: Badge[];
  /** All selectable hobbies */
  hobby_options: HobbyOption[];
  suggestions: Suggestions;
  /** Open pair invites addressed to me */
  invitations: PairSessionOut[];
  /** Quests I created, newest first */
  created_quests: CreatedQuestOut[];
}

export interface MeetupPhotoOut {
  id: string;
  quest_id: string;
  quest_title: string;
  uploaded_at: string;
}

export const PairCancelActionValue = {
  type: "pair_cancel",
} as const;
export type PairCancelAction = typeof PairCancelActionValue;

export interface PairJoinResult {
  session: PairSessionOut;
  completion: CompletionResult;
}

/**
 * Start a pair quest and get a code (replaces your earlier open code).
 */
export interface PairStartAction {
  type: "pair_start";
  /** Invite a suggested username: the code appears on their home screen */
  invite_username?: string | null;
}

export type PlayerQuestInKind =
  (typeof PlayerQuestInKind)[keyof typeof PlayerQuestInKind];

export const PlayerQuestInKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
} as const;

export interface PlayerQuestIn {
  /**
   * @minLength 2
   * @maxLength 120
   */
  title: string;
  /** @maxLength 2000 */
  description?: string;
  location?: string | null;
  kind?: PlayerQuestInKind;
  password?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /** @maxItems 20 */
  steps?: StepIn[];
  /** @maxItems 20 */
  questions?: QuizQuestionIn[];
}

/**
 * Another player on the same quest who opted in to being seen.
 */
export interface Participant {
  username: string;
  display_name: string;
  /** Labels of hobbies you share (may be empty) */
  shared_hobbies: string[];
}

export interface PlayerSearchResult {
  username: string;
  display_name: string;
}

export interface ProfileUpdate {
  /** @maxItems 20 */
  hobbies: string[];
  discoverable: boolean;
}

/**
 * My relation to this player: none, outgoing/incoming request, or friends
 */
export type PublicPlayerFriendStatus =
  (typeof PublicPlayerFriendStatus)[keyof typeof PublicPlayerFriendStatus];

export const PublicPlayerFriendStatus = {
  none: "none",
  outgoing: "outgoing",
  incoming: "incoming",
  friends: "friends",
} as const;

/**
 * What other players may see of a discoverable player.
 */
export interface PublicPlayer {
  username: string;
  display_name: string;
  total_points: number;
  /** Hobby keys, see Me.hobby_options */
  hobbies: string[];
  badges: Badge[];
  /** My relation to this player: none, outgoing/incoming request, or friends */
  friend_status: PublicPlayerFriendStatus;
}

export type QuestOutKind = (typeof QuestOutKind)[keyof typeof QuestOutKind];

export const QuestOutKind = {
  solo: "solo",
  pair: "pair",
  quiz: "quiz",
  multi_step: "multi_step",
  meetup: "meetup",
} as const;

export type QuestOutStatus =
  (typeof QuestOutStatus)[keyof typeof QuestOutStatus];

export const QuestOutStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export type QuestOutMeetupState =
  (typeof QuestOutMeetupState)[keyof typeof QuestOutMeetupState] | null;

export const QuestOutMeetupState = {
  upcoming: "upcoming",
  live: "live",
  past: "past",
  cancelled: "cancelled",
} as const;

export type QuestOutCompletionStatus =
  | (typeof QuestOutCompletionStatus)[keyof typeof QuestOutCompletionStatus]
  | null;

export const QuestOutCompletionStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;

export interface StepOut {
  id: string;
  position: number;
  title: string;
  description: string;
  done: boolean;
}

export interface QuizQuestionOut {
  id: string;
  position: number;
  prompt: string;
  choices: string[];
}

/**
 * The current player's vote (0 = none)
 */
export type QuestVotesMine =
  (typeof QuestVotesMine)[keyof typeof QuestVotesMine];

export const QuestVotesMine = {
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
  NUMBER_0: 0,
} as const;

export interface QuestVotes {
  up: number;
  down: number;
  /** up minus down */
  score: number;
  /** The current player's vote (0 = none) */
  mine: QuestVotesMine;
  /** False for the quest's author */
  can_vote: boolean;
}

export interface QuestOut {
  id: string;
  title: string;
  /** Instructions for the activity */
  description: string;
  location?: string | null;
  /** Reward for completing the quest */
  points: number;
  kind: QuestOutKind;
  status: QuestOutStatus;
  requires_approval: boolean;
  /** Enter the printed code or scan its QR to complete (meetups: to check in) */
  requires_code: boolean;
  /** Enter the creator-set password to complete */
  requires_password: boolean;
  /** Map pin (WGS84) */
  latitude?: number | null;
  /** Map pin (WGS84) */
  longitude?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  meetup_state?: QuestOutMeetupState;
  /** Set for player-created quests */
  author_name?: string | null;
  /** Current player has an approved completion */
  completed: boolean;
  /** UTC time of the current player's completion */
  completed_at?: string | null;
  completion_status?: QuestOutCompletionStatus;
  /** Maintainer's note on a rejected completion */
  review_note?: string | null;
  steps?: StepOut[];
  questions?: QuizQuestionOut[];
  rsvp?: boolean;
  rsvp_count?: number;
  /** I joined this quest (meetups: I said I'm coming) */
  joined?: boolean;
  /** Other players doing this quest right now, named or not */
  participant_count?: number;
  /** Those of them who opted in to suggestions; only set while I'm doing the quest myself */
  participants?: Participant[] | null;
  reported?: boolean;
  /** Up/down votes; only player-created quests can be voted on */
  votes?: QuestVotes | null;
  /** My latest pair session for this quest (host or partner) */
  pair_session?: PairSessionOut | null;
}

export interface QuizResult {
  passed: boolean;
  correct_count: number;
  total: number;
  /** Per question, whether the answer was right */
  correct: boolean[];
}

export interface QuestActionResult {
  /** The quest as it is after the action */
  quest: QuestOut;
  /** Set when the action completed or submitted the quest */
  completion?: CompletionResult | null;
  /** Set for type=quiz */
  quiz?: QuizResult | null;
}

export interface QuestPhotoOut {
  id: string;
  quest_id: string;
  quest_title: string;
  uploaded_at: string;
  is_mine: boolean;
  uploader_username?: string | null;
  uploader_display_name?: string | null;
}

export interface QuizAction {
  type: "quiz";
  /** Chosen choice index per question, in order */
  answers: number[];
}

/**
 * Redeem a printed code or solo password, or check in at a live meetup
 * whose organiser shows the QR code.
 */
export interface RedeemAction {
  type: "redeem";
  /**
   * @minLength 1
   * @maxLength 40
   */
  code: string;
}

export interface ReportAction {
  type: "report";
  /**
   * @minLength 5
   * @maxLength 500
   */
  reason: string;
}

export interface ReportResolution {
  /** Also retire the reported quest */
  retire_quest: boolean;
}

export interface RsvpAction {
  type: "rsvp";
  attending: boolean;
}

/**
 * Mark the next step of a multi-step quest as done.
 */
export interface StepAction {
  type: "step";
  step_id: string;
}

export type VoteActionValue =
  (typeof VoteActionValue)[keyof typeof VoteActionValue];

export const VoteActionValue = {
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
  NUMBER_0: 0,
} as const;

/**
 * Up- or downvote a player-created quest; 0 removes your vote.
 */
export interface VoteAction {
  type: "vote";
  value: VoteActionValue;
}

export type SearchPlayersParams = {
  /**
   * Part of a display name
   * @minLength 2
   * @maxLength 100
   */
  q: string;
};

export type GetLeaderboardParams = {
  /**
   * `global`: all players; `friends`: you and your accepted friends
   */
  scope?: GetLeaderboardScope;
};

export type GetLeaderboardScope =
  (typeof GetLeaderboardScope)[keyof typeof GetLeaderboardScope];

export const GetLeaderboardScope = {
  global: "global",
  friends: "friends",
} as const;

export type AdminListQuestsParams = {
  status?: AdminListQuestsStatus;
};

export type AdminListQuestsStatus =
  (typeof AdminListQuestsStatus)[keyof typeof AdminListQuestsStatus] | null;

export const AdminListQuestsStatus = {
  draft: "draft",
  pending_review: "pending_review",
  published: "published",
  rejected: "rejected",
  retired: "retired",
} as const;

export type AdminListCompletionsParams = {
  status?: AdminListCompletionsStatus;
};

export type AdminListCompletionsStatus =
  (typeof AdminListCompletionsStatus)[keyof typeof AdminListCompletionsStatus];

export const AdminListCompletionsStatus = {
  approved: "approved",
  pending: "pending",
  rejected: "rejected",
} as const;
