/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  MeetupPhotoOut,
  QuestPhotoOut,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listMeetupPhotosResponse200 = {
  data: MeetupPhotoOut[];
  status: 200;
};

export type listMeetupPhotosResponse404 = {
  data: void;
  status: 404;
};

export type listMeetupPhotosResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listMeetupPhotosResponseSuccess = listMeetupPhotosResponse200 & {
  headers: Headers;
};
export type listMeetupPhotosResponseError = (
  listMeetupPhotosResponse404 | listMeetupPhotosResponse422
) & {
  headers: Headers;
};

export type listMeetupPhotosResponse =
  listMeetupPhotosResponseSuccess | listMeetupPhotosResponseError;

export const getListMeetupPhotosUrl = (questId: string) => {
  return `/api/quests/${questId}/photos`;
};

/**
 * List photos attached to a meetup the player can view.
 * @summary List Meetup Photos
 */
export const listMeetupPhotos = async (
  questId: string,
  options?: RequestInit,
): Promise<listMeetupPhotosResponse> => {
  const res = await fetch(getListMeetupPhotosUrl(questId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMeetupPhotosResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listMeetupPhotosResponse;
};

export const getListMeetupPhotosQueryKey = (questId: string) => {
  return [`/api/quests/${questId}/photos`] as const;
};

export const getListMeetupPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof listMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListMeetupPhotosQueryKey(questId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listMeetupPhotos>>
  > = ({ signal }) => listMeetupPhotos(questId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: questId !== null && questId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listMeetupPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListMeetupPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMeetupPhotos>>
>;
export type ListMeetupPhotosQueryError = void | HTTPValidationError;

export function useListMeetupPhotos<
  TData = Awaited<ReturnType<typeof listMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMeetupPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMeetupPhotos>>,
          TError,
          Awaited<ReturnType<typeof listMeetupPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMeetupPhotos<
  TData = Awaited<ReturnType<typeof listMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMeetupPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMeetupPhotos>>,
          TError,
          Awaited<ReturnType<typeof listMeetupPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMeetupPhotos<
  TData = Awaited<ReturnType<typeof listMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Meetup Photos
 */

export function useListMeetupPhotos<
  TData = Awaited<ReturnType<typeof listMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListMeetupPhotosQueryOptions(questId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type listQuestPhotosResponse200 = {
  data: QuestPhotoOut[];
  status: 200;
};

export type listQuestPhotosResponse404 = {
  data: void;
  status: 404;
};

export type listQuestPhotosResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listQuestPhotosResponseSuccess = listQuestPhotosResponse200 & {
  headers: Headers;
};
export type listQuestPhotosResponseError = (
  listQuestPhotosResponse404 | listQuestPhotosResponse422
) & {
  headers: Headers;
};

export type listQuestPhotosResponse =
  listQuestPhotosResponseSuccess | listQuestPhotosResponseError;

export const getListQuestPhotosUrl = (questId: string) => {
  return `/api/quests/${questId}/player-photos`;
};

/**
 * List player-uploaded photos for a meetup, pair, or multi-step quest.
 * @summary List Quest Photos
 */
export const listQuestPhotos = async (
  questId: string,
  options?: RequestInit,
): Promise<listQuestPhotosResponse> => {
  const res = await fetch(getListQuestPhotosUrl(questId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listQuestPhotosResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listQuestPhotosResponse;
};

export const getListQuestPhotosQueryKey = (questId: string) => {
  return [`/api/quests/${questId}/player-photos`] as const;
};

export const getListQuestPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof listQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listQuestPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListQuestPhotosQueryKey(questId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuestPhotos>>> = ({
    signal,
  }) => listQuestPhotos(questId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: questId !== null && questId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listQuestPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQuestPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listQuestPhotos>>
>;
export type ListQuestPhotosQueryError = void | HTTPValidationError;

export function useListQuestPhotos<
  TData = Awaited<ReturnType<typeof listQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listQuestPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestPhotos>>,
          TError,
          Awaited<ReturnType<typeof listQuestPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuestPhotos<
  TData = Awaited<ReturnType<typeof listQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listQuestPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuestPhotos>>,
          TError,
          Awaited<ReturnType<typeof listQuestPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuestPhotos<
  TData = Awaited<ReturnType<typeof listQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listQuestPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Quest Photos
 */

export function useListQuestPhotos<
  TData = Awaited<ReturnType<typeof listQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listQuestPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListQuestPhotosQueryOptions(questId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type uploadQuestPhotoResponse201 = {
  data: QuestPhotoOut;
  status: 201;
};

export type uploadQuestPhotoResponse400 = {
  data: void;
  status: 400;
};

export type uploadQuestPhotoResponse404 = {
  data: void;
  status: 404;
};

export type uploadQuestPhotoResponse413 = {
  data: void;
  status: 413;
};

export type uploadQuestPhotoResponse415 = {
  data: void;
  status: 415;
};

export type uploadQuestPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type uploadQuestPhotoResponseSuccess = uploadQuestPhotoResponse201 & {
  headers: Headers;
};
export type uploadQuestPhotoResponseError = (
  | uploadQuestPhotoResponse400
  | uploadQuestPhotoResponse404
  | uploadQuestPhotoResponse413
  | uploadQuestPhotoResponse415
  | uploadQuestPhotoResponse422
) & {
  headers: Headers;
};

export type uploadQuestPhotoResponse =
  uploadQuestPhotoResponseSuccess | uploadQuestPhotoResponseError;

export const getUploadQuestPhotoUrl = (questId: string) => {
  return `/api/quests/${questId}/player-photos`;
};

/**
 * Let a player add a photo to a visible meetup, pair, or multi-step quest.
 * @summary Upload Quest Photo
 */
export const uploadQuestPhoto = async (
  questId: string,
  options?: RequestInit,
): Promise<uploadQuestPhotoResponse> => {
  const res = await fetch(getUploadQuestPhotoUrl(questId), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadQuestPhotoResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as uploadQuestPhotoResponse;
};

export const getUploadQuestPhotoMutationKey = () =>
  ["uploadQuestPhoto"] as const;

export const getUploadQuestPhotoMutationOptions = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadQuestPhoto>>,
    TError,
    UploadQuestPhotoMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadQuestPhoto>>,
  TError,
  UploadQuestPhotoMutationVariables,
  TContext
> => {
  const mutationKey = getUploadQuestPhotoMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadQuestPhoto>>,
    UploadQuestPhotoMutationVariables
  > = (props) => {
    const { questId } = props ?? {};

    return uploadQuestPhoto(questId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadQuestPhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadQuestPhoto>>
>;

export type UploadQuestPhotoMutationError = void | HTTPValidationError;
export type UploadQuestPhotoMutationVariables = { questId: string };

/**
 * @summary Upload Quest Photo
 */
export const useUploadQuestPhoto = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadQuestPhoto>>,
      TError,
      UploadQuestPhotoMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadQuestPhoto>>,
  TError,
  UploadQuestPhotoMutationVariables,
  TContext
> => {
  return useMutation(getUploadQuestPhotoMutationOptions(options), queryClient);
};
export type getQuestPhotoResponse200 = {
  data: void;
  status: 200;
};

export type getQuestPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getQuestPhotoResponseSuccess = getQuestPhotoResponse200 & {
  headers: Headers;
};
export type getQuestPhotoResponseError = getQuestPhotoResponse422 & {
  headers: Headers;
};

export type getQuestPhotoResponse =
  getQuestPhotoResponseSuccess | getQuestPhotoResponseError;

export const getGetQuestPhotoUrl = (photoId: string) => {
  return `/api/quest-photos/${photoId}`;
};

/**
 * @summary Get Quest Photo
 */
export const getQuestPhoto = async (
  photoId: string,
  options?: RequestInit,
): Promise<getQuestPhotoResponse> => {
  const res = await fetch(getGetQuestPhotoUrl(photoId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getQuestPhotoResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getQuestPhotoResponse;
};

export const getGetQuestPhotoQueryKey = (photoId: string) => {
  return [`/api/quest-photos/${photoId}`] as const;
};

export const getGetQuestPhotoQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuestPhoto>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetQuestPhotoQueryKey(photoId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestPhoto>>> = ({
    signal,
  }) => getQuestPhoto(photoId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: photoId !== null && photoId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQuestPhotoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestPhoto>>
>;
export type GetQuestPhotoQueryError = HTTPValidationError;

export function useGetQuestPhoto<
  TData = Awaited<ReturnType<typeof getQuestPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuestPhoto>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestPhoto>>,
          TError,
          Awaited<ReturnType<typeof getQuestPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestPhoto<
  TData = Awaited<ReturnType<typeof getQuestPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuestPhoto>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestPhoto>>,
          TError,
          Awaited<ReturnType<typeof getQuestPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuestPhoto<
  TData = Awaited<ReturnType<typeof getQuestPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuestPhoto>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Quest Photo
 */

export function useGetQuestPhoto<
  TData = Awaited<ReturnType<typeof getQuestPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuestPhoto>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetQuestPhotoQueryOptions(photoId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type deleteQuestPhotoResponse204 = {
  data: void;
  status: 204;
};

export type deleteQuestPhotoResponse404 = {
  data: void;
  status: 404;
};

export type deleteQuestPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteQuestPhotoResponseSuccess = deleteQuestPhotoResponse204 & {
  headers: Headers;
};
export type deleteQuestPhotoResponseError = (
  deleteQuestPhotoResponse404 | deleteQuestPhotoResponse422
) & {
  headers: Headers;
};

export type deleteQuestPhotoResponse =
  deleteQuestPhotoResponseSuccess | deleteQuestPhotoResponseError;

export const getDeleteQuestPhotoUrl = (questId: string, photoId: string) => {
  return `/api/quests/${questId}/player-photos/${photoId}`;
};

/**
 * Delete a player's own photo from a quest.
 * @summary Delete Quest Photo
 */
export const deleteQuestPhoto = async (
  questId: string,
  photoId: string,
  options?: RequestInit,
): Promise<deleteQuestPhotoResponse> => {
  const res = await fetch(getDeleteQuestPhotoUrl(questId, photoId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteQuestPhotoResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteQuestPhotoResponse;
};

export const getDeleteQuestPhotoMutationKey = () =>
  ["deleteQuestPhoto"] as const;

export const getDeleteQuestPhotoMutationOptions = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuestPhoto>>,
    TError,
    DeleteQuestPhotoMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteQuestPhoto>>,
  TError,
  DeleteQuestPhotoMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteQuestPhotoMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteQuestPhoto>>,
    DeleteQuestPhotoMutationVariables
  > = (props) => {
    const { questId, photoId } = props ?? {};

    return deleteQuestPhoto(questId, photoId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteQuestPhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuestPhoto>>
>;

export type DeleteQuestPhotoMutationError = void | HTTPValidationError;
export type DeleteQuestPhotoMutationVariables = {
  questId: string;
  photoId: string;
};

/**
 * @summary Delete Quest Photo
 */
export const useDeleteQuestPhoto = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteQuestPhoto>>,
      TError,
      DeleteQuestPhotoMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteQuestPhoto>>,
  TError,
  DeleteQuestPhotoMutationVariables,
  TContext
> => {
  return useMutation(getDeleteQuestPhotoMutationOptions(options), queryClient);
};
export type listProfileQuestPhotosResponse200 = {
  data: QuestPhotoOut[];
  status: 200;
};

export type listProfileQuestPhotosResponse404 = {
  data: void;
  status: 404;
};

export type listProfileQuestPhotosResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listProfileQuestPhotosResponseSuccess =
  listProfileQuestPhotosResponse200 & {
    headers: Headers;
  };
export type listProfileQuestPhotosResponseError = (
  listProfileQuestPhotosResponse404 | listProfileQuestPhotosResponse422
) & {
  headers: Headers;
};

export type listProfileQuestPhotosResponse =
  listProfileQuestPhotosResponseSuccess | listProfileQuestPhotosResponseError;

export const getListProfileQuestPhotosUrl = (username: string) => {
  return `/api/players/${username}/quest-photos`;
};

/**
 * List a discoverable player's own photos from completed quests.
 * @summary List Profile Quest Photos
 */
export const listProfileQuestPhotos = async (
  username: string,
  options?: RequestInit,
): Promise<listProfileQuestPhotosResponse> => {
  const res = await fetch(getListProfileQuestPhotosUrl(username), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listProfileQuestPhotosResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProfileQuestPhotosResponse;
};

export const getListProfileQuestPhotosQueryKey = (username: string) => {
  return [`/api/players/${username}/quest-photos`] as const;
};

export const getListProfileQuestPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof listProfileQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileQuestPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListProfileQuestPhotosQueryKey(username);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listProfileQuestPhotos>>
  > = ({ signal }) =>
    listProfileQuestPhotos(username, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listProfileQuestPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListProfileQuestPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listProfileQuestPhotos>>
>;
export type ListProfileQuestPhotosQueryError = void | HTTPValidationError;

export function useListProfileQuestPhotos<
  TData = Awaited<ReturnType<typeof listProfileQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileQuestPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProfileQuestPhotos>>,
          TError,
          Awaited<ReturnType<typeof listProfileQuestPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListProfileQuestPhotos<
  TData = Awaited<ReturnType<typeof listProfileQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileQuestPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProfileQuestPhotos>>,
          TError,
          Awaited<ReturnType<typeof listProfileQuestPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListProfileQuestPhotos<
  TData = Awaited<ReturnType<typeof listProfileQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileQuestPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Profile Quest Photos
 */

export function useListProfileQuestPhotos<
  TData = Awaited<ReturnType<typeof listProfileQuestPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileQuestPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListProfileQuestPhotosQueryOptions(username, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProfileQuestPhotoResponse200 = {
  data: void;
  status: 200;
};

export type getProfileQuestPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getProfileQuestPhotoResponseSuccess =
  getProfileQuestPhotoResponse200 & {
    headers: Headers;
  };
export type getProfileQuestPhotoResponseError =
  getProfileQuestPhotoResponse422 & {
    headers: Headers;
  };

export type getProfileQuestPhotoResponse =
  getProfileQuestPhotoResponseSuccess | getProfileQuestPhotoResponseError;

export const getGetProfileQuestPhotoUrl = (
  username: string,
  photoId: string,
) => {
  return `/api/players/${username}/quest-photos/${photoId}/image`;
};

/**
 * @summary Get Profile Quest Photo
 */
export const getProfileQuestPhoto = async (
  username: string,
  photoId: string,
  options?: RequestInit,
): Promise<getProfileQuestPhotoResponse> => {
  const res = await fetch(getGetProfileQuestPhotoUrl(username, photoId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProfileQuestPhotoResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProfileQuestPhotoResponse;
};

export const getGetProfileQuestPhotoQueryKey = (
  username: string,
  photoId: string,
) => {
  return [`/api/players/${username}/quest-photos/${photoId}/image`] as const;
};

export const getGetProfileQuestPhotoQueryOptions = <
  TData = Awaited<ReturnType<typeof getProfileQuestPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileQuestPhoto>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetProfileQuestPhotoQueryKey(username, photoId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProfileQuestPhoto>>
  > = ({ signal }) =>
    getProfileQuestPhoto(username, photoId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      username !== null &&
      username !== undefined &&
      photoId !== null &&
      photoId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProfileQuestPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileQuestPhotoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfileQuestPhoto>>
>;
export type GetProfileQuestPhotoQueryError = HTTPValidationError;

export function useGetProfileQuestPhoto<
  TData = Awaited<ReturnType<typeof getProfileQuestPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileQuestPhoto>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfileQuestPhoto>>,
          TError,
          Awaited<ReturnType<typeof getProfileQuestPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileQuestPhoto<
  TData = Awaited<ReturnType<typeof getProfileQuestPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileQuestPhoto>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfileQuestPhoto>>,
          TError,
          Awaited<ReturnType<typeof getProfileQuestPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileQuestPhoto<
  TData = Awaited<ReturnType<typeof getProfileQuestPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileQuestPhoto>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Profile Quest Photo
 */

export function useGetProfileQuestPhoto<
  TData = Awaited<ReturnType<typeof getProfileQuestPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileQuestPhoto>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProfileQuestPhotoQueryOptions(
    username,
    photoId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getMeetupPhotoResponse200 = {
  data: void;
  status: 200;
};

export type getMeetupPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMeetupPhotoResponseSuccess = getMeetupPhotoResponse200 & {
  headers: Headers;
};
export type getMeetupPhotoResponseError = getMeetupPhotoResponse422 & {
  headers: Headers;
};

export type getMeetupPhotoResponse =
  getMeetupPhotoResponseSuccess | getMeetupPhotoResponseError;

export const getGetMeetupPhotoUrl = (photoId: string) => {
  return `/api/meetup-photos/${photoId}`;
};

/**
 * Serve a meetup photo when its meetup or attendance is visible.
 * @summary Get Meetup Photo
 */
export const getMeetupPhoto = async (
  photoId: string,
  options?: RequestInit,
): Promise<getMeetupPhotoResponse> => {
  const res = await fetch(getGetMeetupPhotoUrl(photoId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeetupPhotoResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMeetupPhotoResponse;
};

export const getGetMeetupPhotoQueryKey = (photoId: string) => {
  return [`/api/meetup-photos/${photoId}`] as const;
};

export const getGetMeetupPhotoQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeetupPhoto>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeetupPhotoQueryKey(photoId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeetupPhoto>>> = ({
    signal,
  }) => getMeetupPhoto(photoId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: photoId !== null && photoId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeetupPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeetupPhotoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMeetupPhoto>>
>;
export type GetMeetupPhotoQueryError = HTTPValidationError;

export function useGetMeetupPhoto<
  TData = Awaited<ReturnType<typeof getMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeetupPhoto>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetupPhoto>>,
          TError,
          Awaited<ReturnType<typeof getMeetupPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMeetupPhoto<
  TData = Awaited<ReturnType<typeof getMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeetupPhoto>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeetupPhoto>>,
          TError,
          Awaited<ReturnType<typeof getMeetupPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMeetupPhoto<
  TData = Awaited<ReturnType<typeof getMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeetupPhoto>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Meetup Photo
 */

export function useGetMeetupPhoto<
  TData = Awaited<ReturnType<typeof getMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeetupPhoto>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMeetupPhotoQueryOptions(photoId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type listProfileMeetupPhotosResponse200 = {
  data: MeetupPhotoOut[];
  status: 200;
};

export type listProfileMeetupPhotosResponse404 = {
  data: void;
  status: 404;
};

export type listProfileMeetupPhotosResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listProfileMeetupPhotosResponseSuccess =
  listProfileMeetupPhotosResponse200 & {
    headers: Headers;
  };
export type listProfileMeetupPhotosResponseError = (
  listProfileMeetupPhotosResponse404 | listProfileMeetupPhotosResponse422
) & {
  headers: Headers;
};

export type listProfileMeetupPhotosResponse =
  listProfileMeetupPhotosResponseSuccess | listProfileMeetupPhotosResponseError;

export const getListProfileMeetupPhotosUrl = (username: string) => {
  return `/api/players/${username}/meetup-photos`;
};

/**
 * List attended meetup photos only for profiles opted into discovery.
 * @summary List Profile Meetup Photos
 */
export const listProfileMeetupPhotos = async (
  username: string,
  options?: RequestInit,
): Promise<listProfileMeetupPhotosResponse> => {
  const res = await fetch(getListProfileMeetupPhotosUrl(username), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listProfileMeetupPhotosResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listProfileMeetupPhotosResponse;
};

export const getListProfileMeetupPhotosQueryKey = (username: string) => {
  return [`/api/players/${username}/meetup-photos`] as const;
};

export const getListProfileMeetupPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListProfileMeetupPhotosQueryKey(username);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listProfileMeetupPhotos>>
  > = ({ signal }) =>
    listProfileMeetupPhotos(username, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListProfileMeetupPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listProfileMeetupPhotos>>
>;
export type ListProfileMeetupPhotosQueryError = void | HTTPValidationError;

export function useListProfileMeetupPhotos<
  TData = Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
          TError,
          Awaited<ReturnType<typeof listProfileMeetupPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListProfileMeetupPhotos<
  TData = Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
          TError,
          Awaited<ReturnType<typeof listProfileMeetupPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListProfileMeetupPhotos<
  TData = Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Profile Meetup Photos
 */

export function useListProfileMeetupPhotos<
  TData = Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listProfileMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListProfileMeetupPhotosQueryOptions(
    username,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProfileMeetupPhotoResponse200 = {
  data: void;
  status: 200;
};

export type getProfileMeetupPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getProfileMeetupPhotoResponseSuccess =
  getProfileMeetupPhotoResponse200 & {
    headers: Headers;
  };
export type getProfileMeetupPhotoResponseError =
  getProfileMeetupPhotoResponse422 & {
    headers: Headers;
  };

export type getProfileMeetupPhotoResponse =
  getProfileMeetupPhotoResponseSuccess | getProfileMeetupPhotoResponseError;

export const getGetProfileMeetupPhotoUrl = (
  username: string,
  photoId: string,
) => {
  return `/api/players/${username}/meetup-photos/${photoId}/image`;
};

/**
 * Serve a meetup photo through an opted-in attendee's profile.
 * @summary Get Profile Meetup Photo
 */
export const getProfileMeetupPhoto = async (
  username: string,
  photoId: string,
  options?: RequestInit,
): Promise<getProfileMeetupPhotoResponse> => {
  const res = await fetch(getGetProfileMeetupPhotoUrl(username, photoId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProfileMeetupPhotoResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProfileMeetupPhotoResponse;
};

export const getGetProfileMeetupPhotoQueryKey = (
  username: string,
  photoId: string,
) => {
  return [`/api/players/${username}/meetup-photos/${photoId}/image`] as const;
};

export const getGetProfileMeetupPhotoQueryOptions = <
  TData = Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetProfileMeetupPhotoQueryKey(username, photoId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProfileMeetupPhoto>>
  > = ({ signal }) =>
    getProfileMeetupPhoto(username, photoId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      username !== null &&
      username !== undefined &&
      photoId !== null &&
      photoId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileMeetupPhotoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfileMeetupPhoto>>
>;
export type GetProfileMeetupPhotoQueryError = HTTPValidationError;

export function useGetProfileMeetupPhoto<
  TData = Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
          TError,
          Awaited<ReturnType<typeof getProfileMeetupPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileMeetupPhoto<
  TData = Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
          TError,
          Awaited<ReturnType<typeof getProfileMeetupPhoto>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileMeetupPhoto<
  TData = Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Profile Meetup Photo
 */

export function useGetProfileMeetupPhoto<
  TData = Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
  TError = HTTPValidationError,
>(
  username: string,
  photoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProfileMeetupPhoto>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProfileMeetupPhotoQueryOptions(
    username,
    photoId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type adminListMeetupPhotosResponse200 = {
  data: MeetupPhotoOut[];
  status: 200;
};

export type adminListMeetupPhotosResponse404 = {
  data: void;
  status: 404;
};

export type adminListMeetupPhotosResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type adminListMeetupPhotosResponseSuccess =
  adminListMeetupPhotosResponse200 & {
    headers: Headers;
  };
export type adminListMeetupPhotosResponseError = (
  adminListMeetupPhotosResponse404 | adminListMeetupPhotosResponse422
) & {
  headers: Headers;
};

export type adminListMeetupPhotosResponse =
  adminListMeetupPhotosResponseSuccess | adminListMeetupPhotosResponseError;

export const getAdminListMeetupPhotosUrl = (questId: string) => {
  return `/api/admin/quests/${questId}/photos`;
};

/**
 * @summary Admin List Meetup Photos
 */
export const adminListMeetupPhotos = async (
  questId: string,
  options?: RequestInit,
): Promise<adminListMeetupPhotosResponse> => {
  const res = await fetch(getAdminListMeetupPhotosUrl(questId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminListMeetupPhotosResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as adminListMeetupPhotosResponse;
};

export const getAdminListMeetupPhotosQueryKey = (questId: string) => {
  return [`/api/admin/quests/${questId}/photos`] as const;
};

export const getAdminListMeetupPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminListMeetupPhotosQueryKey(questId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListMeetupPhotos>>
  > = ({ signal }) =>
    adminListMeetupPhotos(questId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: questId !== null && questId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListMeetupPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListMeetupPhotosQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListMeetupPhotos>>
>;
export type AdminListMeetupPhotosQueryError = void | HTTPValidationError;

export function useAdminListMeetupPhotos<
  TData = Awaited<ReturnType<typeof adminListMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListMeetupPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMeetupPhotos>>,
          TError,
          Awaited<ReturnType<typeof adminListMeetupPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListMeetupPhotos<
  TData = Awaited<ReturnType<typeof adminListMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListMeetupPhotos>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMeetupPhotos>>,
          TError,
          Awaited<ReturnType<typeof adminListMeetupPhotos>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListMeetupPhotos<
  TData = Awaited<ReturnType<typeof adminListMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Admin List Meetup Photos
 */

export function useAdminListMeetupPhotos<
  TData = Awaited<ReturnType<typeof adminListMeetupPhotos>>,
  TError = void | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminListMeetupPhotos>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminListMeetupPhotosQueryOptions(questId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type uploadMeetupPhotoResponse201 = {
  data: MeetupPhotoOut;
  status: 201;
};

export type uploadMeetupPhotoResponse400 = {
  data: void;
  status: 400;
};

export type uploadMeetupPhotoResponse404 = {
  data: void;
  status: 404;
};

export type uploadMeetupPhotoResponse413 = {
  data: void;
  status: 413;
};

export type uploadMeetupPhotoResponse415 = {
  data: void;
  status: 415;
};

export type uploadMeetupPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type uploadMeetupPhotoResponseSuccess = uploadMeetupPhotoResponse201 & {
  headers: Headers;
};
export type uploadMeetupPhotoResponseError = (
  | uploadMeetupPhotoResponse400
  | uploadMeetupPhotoResponse404
  | uploadMeetupPhotoResponse413
  | uploadMeetupPhotoResponse415
  | uploadMeetupPhotoResponse422
) & {
  headers: Headers;
};

export type uploadMeetupPhotoResponse =
  uploadMeetupPhotoResponseSuccess | uploadMeetupPhotoResponseError;

export const getUploadMeetupPhotoUrl = (questId: string) => {
  return `/api/admin/quests/${questId}/photos`;
};

/**
 * @summary Upload Meetup Photo
 */
export const uploadMeetupPhoto = async (
  questId: string,
  options?: RequestInit,
): Promise<uploadMeetupPhotoResponse> => {
  const res = await fetch(getUploadMeetupPhotoUrl(questId), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadMeetupPhotoResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as uploadMeetupPhotoResponse;
};

export const getUploadMeetupPhotoMutationKey = () =>
  ["uploadMeetupPhoto"] as const;

export const getUploadMeetupPhotoMutationOptions = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadMeetupPhoto>>,
    TError,
    UploadMeetupPhotoMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadMeetupPhoto>>,
  TError,
  UploadMeetupPhotoMutationVariables,
  TContext
> => {
  const mutationKey = getUploadMeetupPhotoMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadMeetupPhoto>>,
    UploadMeetupPhotoMutationVariables
  > = (props) => {
    const { questId } = props ?? {};

    return uploadMeetupPhoto(questId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMeetupPhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadMeetupPhoto>>
>;

export type UploadMeetupPhotoMutationError = void | HTTPValidationError;
export type UploadMeetupPhotoMutationVariables = { questId: string };

/**
 * @summary Upload Meetup Photo
 */
export const useUploadMeetupPhoto = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadMeetupPhoto>>,
      TError,
      UploadMeetupPhotoMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadMeetupPhoto>>,
  TError,
  UploadMeetupPhotoMutationVariables,
  TContext
> => {
  return useMutation(getUploadMeetupPhotoMutationOptions(options), queryClient);
};
export type deleteMeetupPhotoResponse204 = {
  data: void;
  status: 204;
};

export type deleteMeetupPhotoResponse404 = {
  data: void;
  status: 404;
};

export type deleteMeetupPhotoResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteMeetupPhotoResponseSuccess = deleteMeetupPhotoResponse204 & {
  headers: Headers;
};
export type deleteMeetupPhotoResponseError = (
  deleteMeetupPhotoResponse404 | deleteMeetupPhotoResponse422
) & {
  headers: Headers;
};

export type deleteMeetupPhotoResponse =
  deleteMeetupPhotoResponseSuccess | deleteMeetupPhotoResponseError;

export const getDeleteMeetupPhotoUrl = (questId: string, photoId: string) => {
  return `/api/admin/quests/${questId}/photos/${photoId}`;
};

/**
 * @summary Delete Meetup Photo
 */
export const deleteMeetupPhoto = async (
  questId: string,
  photoId: string,
  options?: RequestInit,
): Promise<deleteMeetupPhotoResponse> => {
  const res = await fetch(getDeleteMeetupPhotoUrl(questId, photoId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMeetupPhotoResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteMeetupPhotoResponse;
};

export const getDeleteMeetupPhotoMutationKey = () =>
  ["deleteMeetupPhoto"] as const;

export const getDeleteMeetupPhotoMutationOptions = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMeetupPhoto>>,
    TError,
    DeleteMeetupPhotoMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMeetupPhoto>>,
  TError,
  DeleteMeetupPhotoMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteMeetupPhotoMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMeetupPhoto>>,
    DeleteMeetupPhotoMutationVariables
  > = (props) => {
    const { questId, photoId } = props ?? {};

    return deleteMeetupPhoto(questId, photoId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMeetupPhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMeetupPhoto>>
>;

export type DeleteMeetupPhotoMutationError = void | HTTPValidationError;
export type DeleteMeetupPhotoMutationVariables = {
  questId: string;
  photoId: string;
};

/**
 * @summary Delete Meetup Photo
 */
export const useDeleteMeetupPhoto = <
  TError = void | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMeetupPhoto>>,
      TError,
      DeleteMeetupPhotoMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMeetupPhoto>>,
  TError,
  DeleteMeetupPhotoMutationVariables,
  TContext
> => {
  return useMutation(getDeleteMeetupPhotoMutationOptions(options), queryClient);
};
