/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  HTTPValidationError,
  PairJoinResult,
  PairSessionOut,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPairCodeResponse200 = {
  data: PairSessionOut;
  status: 200;
};

export type getPairCodeResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getPairCodeResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getPairCodeResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getPairCodeResponseSuccess = getPairCodeResponse200 & {
  headers: Headers;
};
export type getPairCodeResponseError = (
  getPairCodeResponse401 | getPairCodeResponse404 | getPairCodeResponse422
) & {
  headers: Headers;
};

export type getPairCodeResponse =
  getPairCodeResponseSuccess | getPairCodeResponseError;

export const getGetPairCodeUrl = (code: string) => {
  return `/api/pair/${code}`;
};

/**
 * Look up a code before joining (shows quest and host).
 * @summary Get Pair Code
 */
export const getPairCode = async (
  code: string,
  options?: RequestInit,
): Promise<getPairCodeResponse> => {
  const res = await fetch(getGetPairCodeUrl(code), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPairCodeResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPairCodeResponse;
};

export const getGetPairCodeQueryKey = (code: string) => {
  return [`/api/pair/${code}`] as const;
};

export const getGetPairCodeQueryOptions = <
  TData = Awaited<ReturnType<typeof getPairCode>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairCode>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPairCodeQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPairCode>>> = ({
    signal,
  }) => getPairCode(code, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: code !== null && code !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPairCode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPairCodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPairCode>>
>;
export type GetPairCodeQueryError = ErrorResponse | HTTPValidationError;

export function useGetPairCode<
  TData = Awaited<ReturnType<typeof getPairCode>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  code: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairCode>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPairCode>>,
          TError,
          Awaited<ReturnType<typeof getPairCode>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPairCode<
  TData = Awaited<ReturnType<typeof getPairCode>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairCode>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPairCode>>,
          TError,
          Awaited<ReturnType<typeof getPairCode>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPairCode<
  TData = Awaited<ReturnType<typeof getPairCode>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairCode>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Pair Code
 */

export function useGetPairCode<
  TData = Awaited<ReturnType<typeof getPairCode>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  code: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairCode>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPairCodeQueryOptions(code, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type joinPairSessionResponse200 = {
  data: PairJoinResult;
  status: 200;
};

export type joinPairSessionResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type joinPairSessionResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type joinPairSessionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type joinPairSessionResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type joinPairSessionResponse410 = {
  data: ErrorResponse;
  status: 410;
};

export type joinPairSessionResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type joinPairSessionResponseSuccess = joinPairSessionResponse200 & {
  headers: Headers;
};
export type joinPairSessionResponseError = (
  | joinPairSessionResponse400
  | joinPairSessionResponse401
  | joinPairSessionResponse404
  | joinPairSessionResponse409
  | joinPairSessionResponse410
  | joinPairSessionResponse422
) & {
  headers: Headers;
};

export type joinPairSessionResponse =
  joinPairSessionResponseSuccess | joinPairSessionResponseError;

export const getJoinPairSessionUrl = (code: string) => {
  return `/api/pair/${code}`;
};

/**
 * Join a partner's session with their code. Completes the quest for
 * both players; each gets the reward once (none if already completed).
 * @summary Join Pair Session
 */
export const joinPairSession = async (
  code: string,
  options?: RequestInit,
): Promise<joinPairSessionResponse> => {
  const res = await fetch(getJoinPairSessionUrl(code), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: joinPairSessionResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as joinPairSessionResponse;
};

export const getJoinPairSessionMutationKey = () => ["joinPairSession"] as const;

export const getJoinPairSessionMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinPairSession>>,
    TError,
    JoinPairSessionMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof joinPairSession>>,
  TError,
  JoinPairSessionMutationVariables,
  TContext
> => {
  const mutationKey = getJoinPairSessionMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof joinPairSession>>,
    JoinPairSessionMutationVariables
  > = (props) => {
    const { code } = props ?? {};

    return joinPairSession(code, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JoinPairSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof joinPairSession>>
>;

export type JoinPairSessionMutationError = ErrorResponse | HTTPValidationError;
export type JoinPairSessionMutationVariables = { code: string };

/**
 * @summary Join Pair Session
 */
export const useJoinPairSession = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof joinPairSession>>,
      TError,
      JoinPairSessionMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof joinPairSession>>,
  TError,
  JoinPairSessionMutationVariables,
  TContext
> => {
  return useMutation(getJoinPairSessionMutationOptions(options), queryClient);
};
