/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Badge,
  ErrorResponse,
  HTTPValidationError,
  HobbyOption,
  Player,
  ProfileUpdate,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPlayerResponse200 = {
  data: Player;
  status: 200;
};

export type getPlayerResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getPlayerResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getPlayerResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getPlayerResponseSuccess = getPlayerResponse200 & {
  headers: Headers;
};
export type getPlayerResponseError = (
  getPlayerResponse401 | getPlayerResponse404 | getPlayerResponse422
) & {
  headers: Headers;
};

export type getPlayerResponse =
  getPlayerResponseSuccess | getPlayerResponseError;

export const getGetPlayerUrl = (playerId: number) => {
  return `/api/players/${playerId}`;
};

/**
 * A player's public profile.
 *
 * Only players who opted in to suggestions are visible to others; a player
 * can always view themselves.
 * @summary Get Player
 */
export const getPlayer = async (
  playerId: number,
  options?: RequestInit,
): Promise<getPlayerResponse> => {
  const res = await fetch(getGetPlayerUrl(playerId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPlayerResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPlayerResponse;
};

export const getGetPlayerQueryKey = (playerId: number) => {
  return [`/api/players/${playerId}`] as const;
};

export const getGetPlayerQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  playerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlayerQueryKey(playerId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayer>>> = ({
    signal,
  }) => getPlayer(playerId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: playerId !== null && playerId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPlayerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlayer>>
>;
export type GetPlayerQueryError = ErrorResponse | HTTPValidationError;

export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  playerId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer>>,
          TError,
          Awaited<ReturnType<typeof getPlayer>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  playerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer>>,
          TError,
          Awaited<ReturnType<typeof getPlayer>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  playerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Player
 */

export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  playerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPlayerQueryOptions(playerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getMeResponse200 = {
  data: Player;
  status: 200;
};

export type getMeResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = getMeResponse401 & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/api/me`;
};

/**
 * The current player with their total points.
 * @summary Get Me
 */
export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  const res = await fetch(getGetMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getMeResponse;
};

export const getGetMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorResponse;

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Me
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateProfileResponse200 = {
  data: Player;
  status: 200;
};

export type updateProfileResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type updateProfileResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type updateProfileResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateProfileResponseSuccess = updateProfileResponse200 & {
  headers: Headers;
};
export type updateProfileResponseError = (
  updateProfileResponse400 | updateProfileResponse401 | updateProfileResponse422
) & {
  headers: Headers;
};

export type updateProfileResponse =
  updateProfileResponseSuccess | updateProfileResponseError;

export const getUpdateProfileUrl = () => {
  return `/api/me/profile`;
};

/**
 * Set hobbies and whether the player appears in connection suggestions.
 *
 * Send an empty list to remove all hobbies.
 * @summary Update Profile
 */
export const updateProfile = async (
  profileUpdate: ProfileUpdate,
  options?: RequestInit,
): Promise<updateProfileResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getUpdateProfileUrl(), {
    ...options,
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(profileUpdate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateProfileResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateProfileResponse;
};

export const getUpdateProfileMutationKey = () => ["updateProfile"] as const;

export const getUpdateProfileMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    UpdateProfileMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  UpdateProfileMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateProfileMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProfile>>,
    UpdateProfileMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return updateProfile(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProfile>>
>;
export type UpdateProfileMutationBody = ProfileUpdate;
export type UpdateProfileMutationError = ErrorResponse | HTTPValidationError;
export type UpdateProfileMutationVariables = { data: ProfileUpdate };

/**
 * @summary Update Profile
 */
export const useUpdateProfile = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProfile>>,
      TError,
      UpdateProfileMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProfile>>,
  TError,
  UpdateProfileMutationVariables,
  TContext
> => {
  return useMutation(getUpdateProfileMutationOptions(options), queryClient);
};
export type listBadgesResponse200 = {
  data: Badge[];
  status: 200;
};

export type listBadgesResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listBadgesResponseSuccess = listBadgesResponse200 & {
  headers: Headers;
};
export type listBadgesResponseError = listBadgesResponse401 & {
  headers: Headers;
};

export type listBadgesResponse =
  listBadgesResponseSuccess | listBadgesResponseError;

export const getListBadgesUrl = () => {
  return `/api/me/badges`;
};

/**
 * All badges, with whether and when the current player earned them.
 * @summary List Badges
 */
export const listBadges = async (
  options?: RequestInit,
): Promise<listBadgesResponse> => {
  const res = await fetch(getListBadgesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listBadgesResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listBadgesResponse;
};

export const getListBadgesQueryKey = () => {
  return [`/api/me/badges`] as const;
};

export const getListBadgesQueryOptions = <
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listBadges>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListBadgesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listBadges>>> = ({
    signal,
  }) => listBadges({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listBadges>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListBadgesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listBadges>>
>;
export type ListBadgesQueryError = ErrorResponse;

export function useListBadges<
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listBadges>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBadges>>,
          TError,
          Awaited<ReturnType<typeof listBadges>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListBadges<
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listBadges>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBadges>>,
          TError,
          Awaited<ReturnType<typeof listBadges>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListBadges<
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listBadges>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Badges
 */

export function useListBadges<
  TData = Awaited<ReturnType<typeof listBadges>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listBadges>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListBadgesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type listHobbiesResponse200 = {
  data: HobbyOption[];
  status: 200;
};

export type listHobbiesResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listHobbiesResponseSuccess = listHobbiesResponse200 & {
  headers: Headers;
};
export type listHobbiesResponseError = listHobbiesResponse401 & {
  headers: Headers;
};

export type listHobbiesResponse =
  listHobbiesResponseSuccess | listHobbiesResponseError;

export const getListHobbiesUrl = () => {
  return `/api/hobbies`;
};

/**
 * The hobbies a player can choose from.
 * @summary List Hobbies
 */
export const listHobbies = async (
  options?: RequestInit,
): Promise<listHobbiesResponse> => {
  const res = await fetch(getListHobbiesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listHobbiesResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listHobbiesResponse;
};

export const getListHobbiesQueryKey = () => {
  return [`/api/hobbies`] as const;
};

export const getListHobbiesQueryOptions = <
  TData = Awaited<ReturnType<typeof listHobbies>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listHobbies>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListHobbiesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listHobbies>>> = ({
    signal,
  }) => listHobbies({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listHobbies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListHobbiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listHobbies>>
>;
export type ListHobbiesQueryError = ErrorResponse;

export function useListHobbies<
  TData = Awaited<ReturnType<typeof listHobbies>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listHobbies>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listHobbies>>,
          TError,
          Awaited<ReturnType<typeof listHobbies>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListHobbies<
  TData = Awaited<ReturnType<typeof listHobbies>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listHobbies>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listHobbies>>,
          TError,
          Awaited<ReturnType<typeof listHobbies>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListHobbies<
  TData = Awaited<ReturnType<typeof listHobbies>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listHobbies>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Hobbies
 */

export function useListHobbies<
  TData = Awaited<ReturnType<typeof listHobbies>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listHobbies>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListHobbiesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
