/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  HTTPValidationError,
  Leaderboard,
  Me,
  PlayerSearchResult,
  ProfileUpdate,
  PublicPlayer,
  SearchPlayersParams,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getMeResponse200 = {
  data: Me;
  status: 200;
};

export type getMeResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = getMeResponse401 & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/api/me`;
};

/**
 * Everything about the current player: points, badges, hobbies,
 * connection suggestions, open pair invitations and submitted quests.
 * @summary Get Me
 */
export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  const res = await fetch(getGetMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getMeResponse;
};

export const getGetMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorResponse;

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Me
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateMeResponse200 = {
  data: Me;
  status: 200;
};

export type updateMeResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type updateMeResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type updateMeResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateMeResponseSuccess = updateMeResponse200 & {
  headers: Headers;
};
export type updateMeResponseError = (
  updateMeResponse400 | updateMeResponse401 | updateMeResponse422
) & {
  headers: Headers;
};

export type updateMeResponse = updateMeResponseSuccess | updateMeResponseError;

export const getUpdateMeUrl = () => {
  return `/api/me`;
};

/**
 * Set hobbies and whether the player appears in connection suggestions.
 *
 * Send an empty list to remove all hobbies.
 * @summary Update Me
 */
export const updateMe = async (
  profileUpdate: ProfileUpdate,
  options?: RequestInit,
): Promise<updateMeResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getUpdateMeUrl(), {
    ...options,
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(profileUpdate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateMeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateMeResponse;
};

export const getUpdateMeMutationKey = () => ["updateMe"] as const;

export const getUpdateMeMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMe>>,
    TError,
    UpdateMeMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMe>>,
  TError,
  UpdateMeMutationVariables,
  TContext
> => {
  const mutationKey = getUpdateMeMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMe>>,
    UpdateMeMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return updateMe(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMe>>
>;
export type UpdateMeMutationBody = ProfileUpdate;
export type UpdateMeMutationError = ErrorResponse | HTTPValidationError;
export type UpdateMeMutationVariables = { data: ProfileUpdate };

/**
 * @summary Update Me
 */
export const useUpdateMe = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMe>>,
      TError,
      UpdateMeMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateMe>>,
  TError,
  UpdateMeMutationVariables,
  TContext
> => {
  return useMutation(getUpdateMeMutationOptions(options), queryClient);
};
export type dismissSuggestionResponse204 = {
  data: void;
  status: 204;
};

export type dismissSuggestionResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type dismissSuggestionResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type dismissSuggestionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type dismissSuggestionResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type dismissSuggestionResponseSuccess = dismissSuggestionResponse204 & {
  headers: Headers;
};
export type dismissSuggestionResponseError = (
  | dismissSuggestionResponse400
  | dismissSuggestionResponse401
  | dismissSuggestionResponse404
  | dismissSuggestionResponse422
) & {
  headers: Headers;
};

export type dismissSuggestionResponse =
  dismissSuggestionResponseSuccess | dismissSuggestionResponseError;

export const getDismissSuggestionUrl = (username: string) => {
  return `/api/me/suggestions/${username}`;
};

/**
 * Stop suggesting this player (idempotent).
 * @summary Dismiss Suggestion
 */
export const dismissSuggestion = async (
  username: string,
  options?: RequestInit,
): Promise<dismissSuggestionResponse> => {
  const res = await fetch(getDismissSuggestionUrl(username), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dismissSuggestionResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as dismissSuggestionResponse;
};

export const getDismissSuggestionMutationKey = () =>
  ["dismissSuggestion"] as const;

export const getDismissSuggestionMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dismissSuggestion>>,
    TError,
    DismissSuggestionMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dismissSuggestion>>,
  TError,
  DismissSuggestionMutationVariables,
  TContext
> => {
  const mutationKey = getDismissSuggestionMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dismissSuggestion>>,
    DismissSuggestionMutationVariables
  > = (props) => {
    const { username } = props ?? {};

    return dismissSuggestion(username, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DismissSuggestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof dismissSuggestion>>
>;

export type DismissSuggestionMutationError =
  ErrorResponse | HTTPValidationError;
export type DismissSuggestionMutationVariables = { username: string };

/**
 * @summary Dismiss Suggestion
 */
export const useDismissSuggestion = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dismissSuggestion>>,
      TError,
      DismissSuggestionMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dismissSuggestion>>,
  TError,
  DismissSuggestionMutationVariables,
  TContext
> => {
  return useMutation(getDismissSuggestionMutationOptions(options), queryClient);
};
export type searchPlayersResponse200 = {
  data: PlayerSearchResult[];
  status: 200;
};

export type searchPlayersResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type searchPlayersResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type searchPlayersResponseSuccess = searchPlayersResponse200 & {
  headers: Headers;
};
export type searchPlayersResponseError = (
  searchPlayersResponse401 | searchPlayersResponse422
) & {
  headers: Headers;
};

export type searchPlayersResponse =
  searchPlayersResponseSuccess | searchPlayersResponseError;

export const getSearchPlayersUrl = (params: SearchPlayersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/players?${stringifiedParams}`
    : `/api/players`;
};

/**
 * Discoverable players whose name contains the query, A to Z.
 *
 * Same consent rule as profile pages: players who did not opt in to
 * suggestions cannot be found. Never returns the searcher.
 * @summary Search Players
 */
export const searchPlayers = async (
  params: SearchPlayersParams,
  options?: RequestInit,
): Promise<searchPlayersResponse> => {
  const res = await fetch(getSearchPlayersUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchPlayersResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as searchPlayersResponse;
};

export const getSearchPlayersQueryKey = (params?: SearchPlayersParams) => {
  return [`/api/players`, ...(params ? [params] : [])] as const;
};

export const getSearchPlayersQueryOptions = <
  TData = Awaited<ReturnType<typeof searchPlayers>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: SearchPlayersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPlayers>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchPlayersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPlayers>>> = ({
    signal,
  }) => searchPlayers(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchPlayers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchPlayersQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchPlayers>>
>;
export type SearchPlayersQueryError = ErrorResponse | HTTPValidationError;

export function useSearchPlayers<
  TData = Awaited<ReturnType<typeof searchPlayers>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: SearchPlayersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPlayers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPlayers>>,
          TError,
          Awaited<ReturnType<typeof searchPlayers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchPlayers<
  TData = Awaited<ReturnType<typeof searchPlayers>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: SearchPlayersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPlayers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPlayers>>,
          TError,
          Awaited<ReturnType<typeof searchPlayers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchPlayers<
  TData = Awaited<ReturnType<typeof searchPlayers>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: SearchPlayersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPlayers>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Players
 */

export function useSearchPlayers<
  TData = Awaited<ReturnType<typeof searchPlayers>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  params: SearchPlayersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPlayers>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchPlayersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getPlayerResponse200 = {
  data: PublicPlayer;
  status: 200;
};

export type getPlayerResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getPlayerResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getPlayerResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getPlayerResponseSuccess = getPlayerResponse200 & {
  headers: Headers;
};
export type getPlayerResponseError = (
  getPlayerResponse401 | getPlayerResponse404 | getPlayerResponse422
) & {
  headers: Headers;
};

export type getPlayerResponse =
  getPlayerResponseSuccess | getPlayerResponseError;

export const getGetPlayerUrl = (username: string) => {
  return `/api/players/${username}`;
};

/**
 * A player's public profile.
 *
 * Only players who opted in to suggestions are visible to others, except
 * that friends and players with an open request between them can always
 * see each other; a player can always view themselves.
 * @summary Get Player
 */
export const getPlayer = async (
  username: string,
  options?: RequestInit,
): Promise<getPlayerResponse> => {
  const res = await fetch(getGetPlayerUrl(username), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPlayerResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPlayerResponse;
};

export const getGetPlayerQueryKey = (username: string) => {
  return [`/api/players/${username}`] as const;
};

export const getGetPlayerQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlayerQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayer>>> = ({
    signal,
  }) => getPlayer(username, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPlayerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlayer>>
>;
export type GetPlayerQueryError = ErrorResponse | HTTPValidationError;

export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  username: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer>>,
          TError,
          Awaited<ReturnType<typeof getPlayer>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlayer>>,
          TError,
          Awaited<ReturnType<typeof getPlayer>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Player
 */

export function useGetPlayer<
  TData = Awaited<ReturnType<typeof getPlayer>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  username: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPlayerQueryOptions(username, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getLeaderboardResponse200 = {
  data: Leaderboard;
  status: 200;
};

export type getLeaderboardResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getLeaderboardResponseSuccess = getLeaderboardResponse200 & {
  headers: Headers;
};
export type getLeaderboardResponseError = getLeaderboardResponse401 & {
  headers: Headers;
};

export type getLeaderboardResponse =
  getLeaderboardResponseSuccess | getLeaderboardResponseError;

export const getGetLeaderboardUrl = () => {
  return `/api/leaderboard`;
};

/**
 * Players ranked by approved points. Equal points share a rank (1, 1, 3, ...).
 * @summary Get Leaderboard
 */
export const getLeaderboard = async (
  options?: RequestInit,
): Promise<getLeaderboardResponse> => {
  const res = await fetch(getGetLeaderboardUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLeaderboardResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getLeaderboardResponse;
};

export const getGetLeaderboardQueryKey = () => {
  return [`/api/leaderboard`] as const;
};

export const getGetLeaderboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getLeaderboard>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeaderboardQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeaderboard>>> = ({
    signal,
  }) => getLeaderboard({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaderboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeaderboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaderboard>>
>;
export type GetLeaderboardQueryError = ErrorResponse;

export function useGetLeaderboard<
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeaderboard>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaderboard>>,
          TError,
          Awaited<ReturnType<typeof getLeaderboard>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaderboard<
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeaderboard>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaderboard>>,
          TError,
          Awaited<ReturnType<typeof getLeaderboard>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaderboard<
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeaderboard>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Leaderboard
 */

export function useGetLeaderboard<
  TData = Awaited<ReturnType<typeof getLeaderboard>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLeaderboard>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeaderboardQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
