/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  QuestAnswerResult,
  QuestAnswerSubmit,
  QuestCreate,
  QuestInspection,
  QuestRead,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getAllQuestsQuestsGetResponse200 = {
  data: QuestInspection[];
  status: 200;
};

export type getAllQuestsQuestsGetResponseSuccess =
  getAllQuestsQuestsGetResponse200 & {
    headers: Headers;
  };
export type getAllQuestsQuestsGetResponse =
  getAllQuestsQuestsGetResponseSuccess;

export const getGetAllQuestsQuestsGetUrl = () => {
  return `/api/quests`;
};

/**
 * List quests with every assigned participant and successful solver.
 * @summary Get All Quests
 */
export const getAllQuestsQuestsGet = async (
  options?: RequestInit,
): Promise<getAllQuestsQuestsGetResponse> => {
  const res = await fetch(getGetAllQuestsQuestsGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllQuestsQuestsGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAllQuestsQuestsGetResponse;
};

export const getGetAllQuestsQuestsGetQueryKey = () => {
  return [`/api/quests`] as const;
};

export const getGetAllQuestsQuestsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllQuestsQuestsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllQuestsQuestsGet>>
  > = ({ signal }) => getAllQuestsQuestsGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllQuestsQuestsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllQuestsQuestsGet>>
>;
export type GetAllQuestsQuestsGetQueryError = unknown;

export function useGetAllQuestsQuestsGet<
  TData = Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
          TError,
          Awaited<ReturnType<typeof getAllQuestsQuestsGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllQuestsQuestsGet<
  TData = Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
          TError,
          Awaited<ReturnType<typeof getAllQuestsQuestsGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllQuestsQuestsGet<
  TData = Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get All Quests
 */

export function useGetAllQuestsQuestsGet<
  TData = Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllQuestsQuestsGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllQuestsQuestsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createQuestQuestsPostResponse201 = {
  data: QuestRead;
  status: 201;
};

export type createQuestQuestsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createQuestQuestsPostResponseSuccess =
  createQuestQuestsPostResponse201 & {
    headers: Headers;
  };
export type createQuestQuestsPostResponseError =
  createQuestQuestsPostResponse422 & {
    headers: Headers;
  };

export type createQuestQuestsPostResponse =
  createQuestQuestsPostResponseSuccess | createQuestQuestsPostResponseError;

export const getCreateQuestQuestsPostUrl = () => {
  return `/api/quests`;
};

/**
 * Add a quest to the database without requiring user authorization.
 * @summary Create Quest
 */
export const createQuestQuestsPost = async (
  questCreate: QuestCreate,
  options?: RequestInit,
): Promise<createQuestQuestsPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getCreateQuestQuestsPostUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(questCreate),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createQuestQuestsPostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createQuestQuestsPostResponse;
};

export const getCreateQuestQuestsPostMutationKey = () =>
  ["createQuestQuestsPost"] as const;

export const getCreateQuestQuestsPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuestQuestsPost>>,
    TError,
    CreateQuestQuestsPostMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createQuestQuestsPost>>,
  TError,
  CreateQuestQuestsPostMutationVariables,
  TContext
> => {
  const mutationKey = getCreateQuestQuestsPostMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createQuestQuestsPost>>,
    CreateQuestQuestsPostMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createQuestQuestsPost(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateQuestQuestsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createQuestQuestsPost>>
>;
export type CreateQuestQuestsPostMutationBody = QuestCreate;
export type CreateQuestQuestsPostMutationError = HTTPValidationError;
export type CreateQuestQuestsPostMutationVariables = { data: QuestCreate };

/**
 * @summary Create Quest
 */
export const useCreateQuestQuestsPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createQuestQuestsPost>>,
      TError,
      CreateQuestQuestsPostMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createQuestQuestsPost>>,
  TError,
  CreateQuestQuestsPostMutationVariables,
  TContext
> => {
  return useMutation(
    getCreateQuestQuestsPostMutationOptions(options),
    queryClient,
  );
};
export type deleteQuestQuestsQuestIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteQuestQuestsQuestIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteQuestQuestsQuestIdDeleteResponseSuccess =
  deleteQuestQuestsQuestIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteQuestQuestsQuestIdDeleteResponseError =
  deleteQuestQuestsQuestIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteQuestQuestsQuestIdDeleteResponse =
  | deleteQuestQuestsQuestIdDeleteResponseSuccess
  | deleteQuestQuestsQuestIdDeleteResponseError;

export const getDeleteQuestQuestsQuestIdDeleteUrl = (questId: string) => {
  return `/api/quests/${questId}`;
};

/**
 * Delete a quest and its participant and solver records.
 * @summary Delete Quest
 */
export const deleteQuestQuestsQuestIdDelete = async (
  questId: string,
  options?: RequestInit,
): Promise<deleteQuestQuestsQuestIdDeleteResponse> => {
  const res = await fetch(getDeleteQuestQuestsQuestIdDeleteUrl(questId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteQuestQuestsQuestIdDeleteResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteQuestQuestsQuestIdDeleteResponse;
};

export const getDeleteQuestQuestsQuestIdDeleteMutationKey = () =>
  ["deleteQuestQuestsQuestIdDelete"] as const;

export const getDeleteQuestQuestsQuestIdDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuestQuestsQuestIdDelete>>,
    TError,
    DeleteQuestQuestsQuestIdDeleteMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteQuestQuestsQuestIdDelete>>,
  TError,
  DeleteQuestQuestsQuestIdDeleteMutationVariables,
  TContext
> => {
  const mutationKey = getDeleteQuestQuestsQuestIdDeleteMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteQuestQuestsQuestIdDelete>>,
    DeleteQuestQuestsQuestIdDeleteMutationVariables
  > = (props) => {
    const { questId } = props ?? {};

    return deleteQuestQuestsQuestIdDelete(questId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteQuestQuestsQuestIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuestQuestsQuestIdDelete>>
>;

export type DeleteQuestQuestsQuestIdDeleteMutationError = HTTPValidationError;
export type DeleteQuestQuestsQuestIdDeleteMutationVariables = {
  questId: string;
};

/**
 * @summary Delete Quest
 */
export const useDeleteQuestQuestsQuestIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteQuestQuestsQuestIdDelete>>,
      TError,
      DeleteQuestQuestsQuestIdDeleteMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteQuestQuestsQuestIdDelete>>,
  TError,
  DeleteQuestQuestsQuestIdDeleteMutationVariables,
  TContext
> => {
  return useMutation(
    getDeleteQuestQuestsQuestIdDeleteMutationOptions(options),
    queryClient,
  );
};
export type getNextQuestQuestsNextGetResponse200 = {
  data: QuestRead;
  status: 200;
};

export type getNextQuestQuestsNextGetResponseSuccess =
  getNextQuestQuestsNextGetResponse200 & {
    headers: Headers;
  };
export type getNextQuestQuestsNextGetResponse =
  getNextQuestQuestsNextGetResponseSuccess;

export const getGetNextQuestQuestsNextGetUrl = () => {
  return `/api/quests/next`;
};

/**
 * Return an unsolved quest, cycling missed quests after other quests.
 * @summary Get Next Quest
 */
export const getNextQuestQuestsNextGet = async (
  options?: RequestInit,
): Promise<getNextQuestQuestsNextGetResponse> => {
  const res = await fetch(getGetNextQuestQuestsNextGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNextQuestQuestsNextGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getNextQuestQuestsNextGetResponse;
};

export const getGetNextQuestQuestsNextGetQueryKey = () => {
  return [`/api/quests/next`] as const;
};

export const getGetNextQuestQuestsNextGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNextQuestQuestsNextGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>
  > = ({ signal }) => getNextQuestQuestsNextGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNextQuestQuestsNextGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>
>;
export type GetNextQuestQuestsNextGetQueryError = unknown;

export function useGetNextQuestQuestsNextGet<
  TData = Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
          TError,
          Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNextQuestQuestsNextGet<
  TData = Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
          TError,
          Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNextQuestQuestsNextGet<
  TData = Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Next Quest
 */

export function useGetNextQuestQuestsNextGet<
  TData = Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextQuestQuestsNextGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNextQuestQuestsNextGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type submitQuestAnswerQuestsQuestIdAnswerPostResponse200 = {
  data: QuestAnswerResult;
  status: 200;
};

export type submitQuestAnswerQuestsQuestIdAnswerPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type submitQuestAnswerQuestsQuestIdAnswerPostResponseSuccess =
  submitQuestAnswerQuestsQuestIdAnswerPostResponse200 & {
    headers: Headers;
  };
export type submitQuestAnswerQuestsQuestIdAnswerPostResponseError =
  submitQuestAnswerQuestsQuestIdAnswerPostResponse422 & {
    headers: Headers;
  };

export type submitQuestAnswerQuestsQuestIdAnswerPostResponse =
  | submitQuestAnswerQuestsQuestIdAnswerPostResponseSuccess
  | submitQuestAnswerQuestsQuestIdAnswerPostResponseError;

export const getSubmitQuestAnswerQuestsQuestIdAnswerPostUrl = (
  questId: string,
) => {
  return `/api/quests/${questId}/answer`;
};

/**
 * Check an answer submitted for a quest assigned to the user.
 * @summary Submit Quest Answer
 */
export const submitQuestAnswerQuestsQuestIdAnswerPost = async (
  questId: string,
  questAnswerSubmit: QuestAnswerSubmit,
  options?: RequestInit,
): Promise<submitQuestAnswerQuestsQuestIdAnswerPostResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(
    getSubmitQuestAnswerQuestsQuestIdAnswerPostUrl(questId),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(questAnswerSubmit),
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitQuestAnswerQuestsQuestIdAnswerPostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as submitQuestAnswerQuestsQuestIdAnswerPostResponse;
};

export const getSubmitQuestAnswerQuestsQuestIdAnswerPostMutationKey = () =>
  ["submitQuestAnswerQuestsQuestIdAnswerPost"] as const;

export const getSubmitQuestAnswerQuestsQuestIdAnswerPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuestAnswerQuestsQuestIdAnswerPost>>,
    TError,
    SubmitQuestAnswerQuestsQuestIdAnswerPostMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuestAnswerQuestsQuestIdAnswerPost>>,
  TError,
  SubmitQuestAnswerQuestsQuestIdAnswerPostMutationVariables,
  TContext
> => {
  const mutationKey = getSubmitQuestAnswerQuestsQuestIdAnswerPostMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuestAnswerQuestsQuestIdAnswerPost>>,
    SubmitQuestAnswerQuestsQuestIdAnswerPostMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return submitQuestAnswerQuestsQuestIdAnswerPost(
      questId,
      data,
      fetchOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitQuestAnswerQuestsQuestIdAnswerPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof submitQuestAnswerQuestsQuestIdAnswerPost>>
  >;
export type SubmitQuestAnswerQuestsQuestIdAnswerPostMutationBody =
  QuestAnswerSubmit;
export type SubmitQuestAnswerQuestsQuestIdAnswerPostMutationError =
  HTTPValidationError;
export type SubmitQuestAnswerQuestsQuestIdAnswerPostMutationVariables = {
  questId: string;
  data: QuestAnswerSubmit;
};

/**
 * @summary Submit Quest Answer
 */
export const useSubmitQuestAnswerQuestsQuestIdAnswerPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitQuestAnswerQuestsQuestIdAnswerPost>>,
      TError,
      SubmitQuestAnswerQuestsQuestIdAnswerPostMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitQuestAnswerQuestsQuestIdAnswerPost>>,
  TError,
  SubmitQuestAnswerQuestsQuestIdAnswerPostMutationVariables,
  TContext
> => {
  return useMutation(
    getSubmitQuestAnswerQuestsQuestIdAnswerPostMutationOptions(options),
    queryClient,
  );
};
