/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CompleteAction,
  ErrorResponse,
  HTTPValidationError,
  PairCancelAction,
  PairStartAction,
  QuestActionResult,
  QuestOut,
  QuestSubmission,
  QuizAction,
  RedeemAction,
  ReportAction,
  RsvpAction,
  StepAction,
  SubmissionOut,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listQuestsResponse200 = {
  data: QuestOut[];
  status: 200;
};

export type listQuestsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listQuestsResponseSuccess = listQuestsResponse200 & {
  headers: Headers;
};
export type listQuestsResponseError = listQuestsResponse401 & {
  headers: Headers;
};

export type listQuestsResponse =
  listQuestsResponseSuccess | listQuestsResponseError;

export const getListQuestsUrl = () => {
  return `/api/quests`;
};

/**
 * All published quests with the current player's progress.
 * @summary List Quests
 */
export const listQuests = async (
  options?: RequestInit,
): Promise<listQuestsResponse> => {
  const res = await fetch(getListQuestsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listQuestsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listQuestsResponse;
};

export const getListQuestsQueryKey = () => {
  return [`/api/quests`] as const;
};

export const getListQuestsQueryOptions = <
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQuestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuests>>> = ({
    signal,
  }) => listQuests({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listQuests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQuestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listQuests>>
>;
export type ListQuestsQueryError = ErrorResponse;

export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuests>>,
          TError,
          Awaited<ReturnType<typeof listQuests>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuests>>,
          TError,
          Awaited<ReturnType<typeof listQuests>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Quests
 */

export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListQuestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type submitQuestResponse201 = {
  data: SubmissionOut;
  status: 201;
};

export type submitQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type submitQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type submitQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type submitQuestResponseSuccess = submitQuestResponse201 & {
  headers: Headers;
};
export type submitQuestResponseError = (
  submitQuestResponse401 | submitQuestResponse409 | submitQuestResponse422
) & {
  headers: Headers;
};

export type submitQuestResponse =
  submitQuestResponseSuccess | submitQuestResponseError;

export const getSubmitQuestUrl = () => {
  return `/api/quests`;
};

/**
 * Propose a new solo quest. A maintainer reviews it before it is published.
 * @summary Submit Quest
 */
export const submitQuest = async (
  questSubmission: QuestSubmission,
  options?: RequestInit,
): Promise<submitQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getSubmitQuestUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(questSubmission),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as submitQuestResponse;
};

export const getSubmitQuestMutationKey = () => ["submitQuest"] as const;

export const getSubmitQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuest>>,
    TError,
    SubmitQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuest>>,
  TError,
  SubmitQuestMutationVariables,
  TContext
> => {
  const mutationKey = getSubmitQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuest>>,
    SubmitQuestMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return submitQuest(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitQuest>>
>;
export type SubmitQuestMutationBody = QuestSubmission;
export type SubmitQuestMutationError = ErrorResponse | HTTPValidationError;
export type SubmitQuestMutationVariables = { data: QuestSubmission };

/**
 * @summary Submit Quest
 */
export const useSubmitQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitQuest>>,
      TError,
      SubmitQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitQuest>>,
  TError,
  SubmitQuestMutationVariables,
  TContext
> => {
  return useMutation(getSubmitQuestMutationOptions(options), queryClient);
};
export type getQuestResponse200 = {
  data: QuestOut;
  status: 200;
};

export type getQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getQuestResponseSuccess = getQuestResponse200 & {
  headers: Headers;
};
export type getQuestResponseError = (
  getQuestResponse401 | getQuestResponse404 | getQuestResponse422
) & {
  headers: Headers;
};

export type getQuestResponse = getQuestResponseSuccess | getQuestResponseError;

export const getGetQuestUrl = (questId: string) => {
  return `/api/quests/${questId}`;
};

/**
 * One quest with full instructions and the current player's progress
 * (including their latest pair session).
 *
 * Also returns retired quests the player completed and their own submissions.
 * @summary Get Quest
 */
export const getQuest = async (
  questId: string,
  options?: RequestInit,
): Promise<getQuestResponse> => {
  const res = await fetch(getGetQuestUrl(questId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getQuestResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getQuestResponse;
};

export const getGetQuestQueryKey = (questId: string) => {
  return [`/api/quests/${questId}`] as const;
};

export const getGetQuestQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetQuestQueryKey(questId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuest>>> = ({
    signal,
  }) => getQuest(questId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: questId !== null && questId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetQuestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuest>>
>;
export type GetQuestQueryError = ErrorResponse | HTTPValidationError;

export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuest>>,
          TError,
          Awaited<ReturnType<typeof getQuest>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuest>>,
          TError,
          Awaited<ReturnType<typeof getQuest>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Quest
 */

export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetQuestQueryOptions(questId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type actOnQuestResponse200 = {
  data: QuestActionResult;
  status: 200;
};

export type actOnQuestResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type actOnQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type actOnQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type actOnQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type actOnQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type actOnQuestResponseSuccess = actOnQuestResponse200 & {
  headers: Headers;
};
export type actOnQuestResponseError = (
  | actOnQuestResponse400
  | actOnQuestResponse401
  | actOnQuestResponse404
  | actOnQuestResponse409
  | actOnQuestResponse422
) & {
  headers: Headers;
};

export type actOnQuestResponse =
  actOnQuestResponseSuccess | actOnQuestResponseError;

export const getActOnQuestUrl = (questId: string) => {
  return `/api/quests/${questId}/actions`;
};

/**
 * Do something with a quest; `type` picks the action:
 *
 * - `complete`: complete a solo quest or check in at a live meetup
 *   (idempotent; approval quests create a pending completion).
 * - `redeem`: complete a code-verified solo quest with its printed code,
 *   or check in at a live meetup by scanning its QR code.
 * - `quiz`: check answers; all must be right, retries are unlimited.
 * - `step`: mark the next step of a multi-step quest done (in order).
 * - `rsvp`: say you're coming to a meetup (`attending: false` withdraws).
 * - `report`: report inappropriate content to the maintainers.
 * - `pair_start`: get a code for your partner (optionally invite a
 *   suggested player); replaces your earlier open code.
 * - `pair_cancel`: cancel your open code (idempotent).
 *
 * Returns the quest as it is afterwards, plus the completion (and quiz
 * result) when the action completed or submitted the quest.
 * @summary Act On Quest
 */
export const actOnQuest = async (
  questId: string,
  completeActionRedeemActionQuizActionStepActionRsvpActionReportActionPairStartActionPairCancelAction:
    | CompleteAction
    | RedeemAction
    | QuizAction
    | StepAction
    | RsvpAction
    | ReportAction
    | PairStartAction
    | PairCancelAction,
  options?: RequestInit,
): Promise<actOnQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getActOnQuestUrl(questId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(
      completeActionRedeemActionQuizActionStepActionRsvpActionReportActionPairStartActionPairCancelAction,
    ),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: actOnQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as actOnQuestResponse;
};

export const getActOnQuestMutationKey = () => ["actOnQuest"] as const;

export const getActOnQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof actOnQuest>>,
    TError,
    ActOnQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof actOnQuest>>,
  TError,
  ActOnQuestMutationVariables,
  TContext
> => {
  const mutationKey = getActOnQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof actOnQuest>>,
    ActOnQuestMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return actOnQuest(questId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ActOnQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof actOnQuest>>
>;
export type ActOnQuestMutationBody =
  | CompleteAction
  | RedeemAction
  | QuizAction
  | StepAction
  | RsvpAction
  | ReportAction
  | PairStartAction
  | PairCancelAction;
export type ActOnQuestMutationError = ErrorResponse | HTTPValidationError;
export type ActOnQuestMutationVariables = {
  questId: string;
  data:
    | CompleteAction
    | RedeemAction
    | QuizAction
    | StepAction
    | RsvpAction
    | ReportAction
    | PairStartAction
    | PairCancelAction;
};

/**
 * @summary Act On Quest
 */
export const useActOnQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof actOnQuest>>,
      TError,
      ActOnQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof actOnQuest>>,
  TError,
  ActOnQuestMutationVariables,
  TContext
> => {
  return useMutation(getActOnQuestMutationOptions(options), queryClient);
};
