/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Campus Voyager
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CodeRedemption,
  CompleteRequest,
  CompletionResult,
  ErrorResponse,
  HTTPValidationError,
  QuestOut,
  QuestSubmission,
  QuizResult,
  QuizSubmission,
  ReportRequest,
  RsvpResult,
  StepResult,
  SubmissionOut,
} from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listQuestsResponse200 = {
  data: QuestOut[];
  status: 200;
};

export type listQuestsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listQuestsResponseSuccess = listQuestsResponse200 & {
  headers: Headers;
};
export type listQuestsResponseError = listQuestsResponse401 & {
  headers: Headers;
};

export type listQuestsResponse =
  listQuestsResponseSuccess | listQuestsResponseError;

export const getListQuestsUrl = () => {
  return `/api/quests`;
};

/**
 * All published quests with the current player's progress.
 * @summary List Quests
 */
export const listQuests = async (
  options?: RequestInit,
): Promise<listQuestsResponse> => {
  const res = await fetch(getListQuestsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listQuestsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listQuestsResponse;
};

export const getListQuestsQueryKey = () => {
  return [`/api/quests`] as const;
};

export const getListQuestsQueryOptions = <
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQuestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuests>>> = ({
    signal,
  }) => listQuests({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listQuests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQuestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listQuests>>
>;
export type ListQuestsQueryError = ErrorResponse;

export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuests>>,
          TError,
          Awaited<ReturnType<typeof listQuests>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuests>>,
          TError,
          Awaited<ReturnType<typeof listQuests>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Quests
 */

export function useListQuests<
  TData = Awaited<ReturnType<typeof listQuests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listQuests>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListQuestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getQuestResponse200 = {
  data: QuestOut;
  status: 200;
};

export type getQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type getQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getQuestResponseSuccess = getQuestResponse200 & {
  headers: Headers;
};
export type getQuestResponseError = (
  getQuestResponse401 | getQuestResponse404 | getQuestResponse422
) & {
  headers: Headers;
};

export type getQuestResponse = getQuestResponseSuccess | getQuestResponseError;

export const getGetQuestUrl = (questId: number) => {
  return `/api/quests/${questId}`;
};

/**
 * One quest with full instructions and the current player's progress.
 *
 * Also returns retired quests the player completed and their own submissions.
 * @summary Get Quest
 */
export const getQuest = async (
  questId: number,
  options?: RequestInit,
): Promise<getQuestResponse> => {
  const res = await fetch(getGetQuestUrl(questId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getQuestResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getQuestResponse;
};

export const getGetQuestQueryKey = (questId: number) => {
  return [`/api/quests/${questId}`] as const;
};

export const getGetQuestQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetQuestQueryKey(questId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuest>>> = ({
    signal,
  }) => getQuest(questId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: questId !== null && questId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetQuestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuest>>
>;
export type GetQuestQueryError = ErrorResponse | HTTPValidationError;

export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuest>>,
          TError,
          Awaited<ReturnType<typeof getQuest>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuest>>,
          TError,
          Awaited<ReturnType<typeof getQuest>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Quest
 */

export function useGetQuest<
  TData = Awaited<ReturnType<typeof getQuest>>,
  TError = ErrorResponse | HTTPValidationError,
>(
  questId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuest>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetQuestQueryOptions(questId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type completeQuestResponse200 = {
  data: CompletionResult;
  status: 200;
};

export type completeQuestResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type completeQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type completeQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type completeQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type completeQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type completeQuestResponseSuccess = completeQuestResponse200 & {
  headers: Headers;
};
export type completeQuestResponseError = (
  | completeQuestResponse400
  | completeQuestResponse401
  | completeQuestResponse404
  | completeQuestResponse409
  | completeQuestResponse422
) & {
  headers: Headers;
};

export type completeQuestResponse =
  completeQuestResponseSuccess | completeQuestResponseError;

export const getCompleteQuestUrl = (questId: number) => {
  return `/api/quests/${questId}/complete`;
};

/**
 * Complete a solo quest, or check in at a live meetup.
 *
 * Idempotent: completing again returns the existing completion with
 * `already_completed: true` and `points_awarded: 0`. Quests with
 * `requires_approval` create a pending completion that awards points
 * only once a maintainer approves it.
 * @summary Complete Quest
 */
export const completeQuest = async (
  questId: number,
  completeRequestNull?: CompleteRequest | null,
  options?: RequestInit,
): Promise<completeQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getCompleteQuestUrl(questId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(completeRequestNull),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: completeQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as completeQuestResponse;
};

export const getCompleteQuestMutationKey = () => ["completeQuest"] as const;

export const getCompleteQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeQuest>>,
    TError,
    CompleteQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeQuest>>,
  TError,
  CompleteQuestMutationVariables,
  TContext
> => {
  const mutationKey = getCompleteQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeQuest>>,
    CompleteQuestMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return completeQuest(questId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompleteQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeQuest>>
>;
export type CompleteQuestMutationBody = CompleteRequest | null | undefined;
export type CompleteQuestMutationError = ErrorResponse | HTTPValidationError;
export type CompleteQuestMutationVariables = {
  questId: number;
  data?: CompleteRequest | null;
};

/**
 * @summary Complete Quest
 */
export const useCompleteQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeQuest>>,
      TError,
      CompleteQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof completeQuest>>,
  TError,
  CompleteQuestMutationVariables,
  TContext
> => {
  return useMutation(getCompleteQuestMutationOptions(options), queryClient);
};
export type redeemQuestCodeResponse200 = {
  data: CompletionResult;
  status: 200;
};

export type redeemQuestCodeResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type redeemQuestCodeResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type redeemQuestCodeResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type redeemQuestCodeResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type redeemQuestCodeResponseSuccess = redeemQuestCodeResponse200 & {
  headers: Headers;
};
export type redeemQuestCodeResponseError = (
  | redeemQuestCodeResponse400
  | redeemQuestCodeResponse401
  | redeemQuestCodeResponse404
  | redeemQuestCodeResponse422
) & {
  headers: Headers;
};

export type redeemQuestCodeResponse =
  redeemQuestCodeResponseSuccess | redeemQuestCodeResponseError;

export const getRedeemQuestCodeUrl = (questId: number) => {
  return `/api/quests/${questId}/redeem`;
};

/**
 * Redeem a printed code, once per player, for a code-verified solo quest.
 * @summary Redeem Quest Code
 */
export const redeemQuestCode = async (
  questId: number,
  codeRedemption: CodeRedemption,
  options?: RequestInit,
): Promise<redeemQuestCodeResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getRedeemQuestCodeUrl(questId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(codeRedemption),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: redeemQuestCodeResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as redeemQuestCodeResponse;
};

export const getRedeemQuestCodeMutationKey = () => ["redeemQuestCode"] as const;

export const getRedeemQuestCodeMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof redeemQuestCode>>,
    TError,
    RedeemQuestCodeMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof redeemQuestCode>>,
  TError,
  RedeemQuestCodeMutationVariables,
  TContext
> => {
  const mutationKey = getRedeemQuestCodeMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof redeemQuestCode>>,
    RedeemQuestCodeMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return redeemQuestCode(questId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RedeemQuestCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof redeemQuestCode>>
>;
export type RedeemQuestCodeMutationBody = CodeRedemption;
export type RedeemQuestCodeMutationError = ErrorResponse | HTTPValidationError;
export type RedeemQuestCodeMutationVariables = {
  questId: number;
  data: CodeRedemption;
};

/**
 * @summary Redeem Quest Code
 */
export const useRedeemQuestCode = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof redeemQuestCode>>,
      TError,
      RedeemQuestCodeMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof redeemQuestCode>>,
  TError,
  RedeemQuestCodeMutationVariables,
  TContext
> => {
  return useMutation(getRedeemQuestCodeMutationOptions(options), queryClient);
};
export type submitQuizResponse200 = {
  data: QuizResult;
  status: 200;
};

export type submitQuizResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type submitQuizResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type submitQuizResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type submitQuizResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type submitQuizResponseSuccess = submitQuizResponse200 & {
  headers: Headers;
};
export type submitQuizResponseError = (
  | submitQuizResponse400
  | submitQuizResponse401
  | submitQuizResponse404
  | submitQuizResponse422
) & {
  headers: Headers;
};

export type submitQuizResponse =
  submitQuizResponseSuccess | submitQuizResponseError;

export const getSubmitQuizUrl = (questId: number) => {
  return `/api/quests/${questId}/quiz`;
};

/**
 * Check quiz answers. All must be right to pass; retries are unlimited
 * and the reward is granted only once.
 * @summary Submit Quiz
 */
export const submitQuiz = async (
  questId: number,
  quizSubmission: QuizSubmission,
  options?: RequestInit,
): Promise<submitQuizResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getSubmitQuizUrl(questId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(quizSubmission),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitQuizResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as submitQuizResponse;
};

export const getSubmitQuizMutationKey = () => ["submitQuiz"] as const;

export const getSubmitQuizMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuiz>>,
    TError,
    SubmitQuizMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuiz>>,
  TError,
  SubmitQuizMutationVariables,
  TContext
> => {
  const mutationKey = getSubmitQuizMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuiz>>,
    SubmitQuizMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return submitQuiz(questId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitQuizMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitQuiz>>
>;
export type SubmitQuizMutationBody = QuizSubmission;
export type SubmitQuizMutationError = ErrorResponse | HTTPValidationError;
export type SubmitQuizMutationVariables = {
  questId: number;
  data: QuizSubmission;
};

/**
 * @summary Submit Quiz
 */
export const useSubmitQuiz = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitQuiz>>,
      TError,
      SubmitQuizMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitQuiz>>,
  TError,
  SubmitQuizMutationVariables,
  TContext
> => {
  return useMutation(getSubmitQuizMutationOptions(options), queryClient);
};
export type completeStepResponse200 = {
  data: StepResult;
  status: 200;
};

export type completeStepResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type completeStepResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type completeStepResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type completeStepResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type completeStepResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type completeStepResponseSuccess = completeStepResponse200 & {
  headers: Headers;
};
export type completeStepResponseError = (
  | completeStepResponse400
  | completeStepResponse401
  | completeStepResponse404
  | completeStepResponse409
  | completeStepResponse422
) & {
  headers: Headers;
};

export type completeStepResponse =
  completeStepResponseSuccess | completeStepResponseError;

export const getCompleteStepUrl = (questId: number, stepId: number) => {
  return `/api/quests/${questId}/steps/${stepId}/complete`;
};

/**
 * Mark the next step of a multi-step quest as done.
 *
 * Steps must be done in order. Finishing the last step completes the quest;
 * points are only awarded for the whole quest, not per step.
 * @summary Complete Step
 */
export const completeStep = async (
  questId: number,
  stepId: number,
  options?: RequestInit,
): Promise<completeStepResponse> => {
  const res = await fetch(getCompleteStepUrl(questId, stepId), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: completeStepResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as completeStepResponse;
};

export const getCompleteStepMutationKey = () => ["completeStep"] as const;

export const getCompleteStepMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeStep>>,
    TError,
    CompleteStepMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeStep>>,
  TError,
  CompleteStepMutationVariables,
  TContext
> => {
  const mutationKey = getCompleteStepMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeStep>>,
    CompleteStepMutationVariables
  > = (props) => {
    const { questId, stepId } = props ?? {};

    return completeStep(questId, stepId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompleteStepMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeStep>>
>;

export type CompleteStepMutationError = ErrorResponse | HTTPValidationError;
export type CompleteStepMutationVariables = { questId: number; stepId: number };

/**
 * @summary Complete Step
 */
export const useCompleteStep = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeStep>>,
      TError,
      CompleteStepMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof completeStep>>,
  TError,
  CompleteStepMutationVariables,
  TContext
> => {
  return useMutation(getCompleteStepMutationOptions(options), queryClient);
};
export type joinMeetupResponse200 = {
  data: RsvpResult;
  status: 200;
};

export type joinMeetupResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type joinMeetupResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type joinMeetupResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type joinMeetupResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type joinMeetupResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type joinMeetupResponseSuccess = joinMeetupResponse200 & {
  headers: Headers;
};
export type joinMeetupResponseError = (
  | joinMeetupResponse400
  | joinMeetupResponse401
  | joinMeetupResponse404
  | joinMeetupResponse409
  | joinMeetupResponse422
) & {
  headers: Headers;
};

export type joinMeetupResponse =
  joinMeetupResponseSuccess | joinMeetupResponseError;

export const getJoinMeetupUrl = (questId: number) => {
  return `/api/quests/${questId}/rsvp`;
};

/**
 * Say you're coming to a meetup (optional; check-in works without it).
 * @summary Join Meetup
 */
export const joinMeetup = async (
  questId: number,
  options?: RequestInit,
): Promise<joinMeetupResponse> => {
  const res = await fetch(getJoinMeetupUrl(questId), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: joinMeetupResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as joinMeetupResponse;
};

export const getJoinMeetupMutationKey = () => ["joinMeetup"] as const;

export const getJoinMeetupMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinMeetup>>,
    TError,
    JoinMeetupMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof joinMeetup>>,
  TError,
  JoinMeetupMutationVariables,
  TContext
> => {
  const mutationKey = getJoinMeetupMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof joinMeetup>>,
    JoinMeetupMutationVariables
  > = (props) => {
    const { questId } = props ?? {};

    return joinMeetup(questId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JoinMeetupMutationResult = NonNullable<
  Awaited<ReturnType<typeof joinMeetup>>
>;

export type JoinMeetupMutationError = ErrorResponse | HTTPValidationError;
export type JoinMeetupMutationVariables = { questId: number };

/**
 * @summary Join Meetup
 */
export const useJoinMeetup = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof joinMeetup>>,
      TError,
      JoinMeetupMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof joinMeetup>>,
  TError,
  JoinMeetupMutationVariables,
  TContext
> => {
  return useMutation(getJoinMeetupMutationOptions(options), queryClient);
};
export type leaveMeetupResponse200 = {
  data: RsvpResult;
  status: 200;
};

export type leaveMeetupResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type leaveMeetupResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type leaveMeetupResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type leaveMeetupResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type leaveMeetupResponseSuccess = leaveMeetupResponse200 & {
  headers: Headers;
};
export type leaveMeetupResponseError = (
  | leaveMeetupResponse400
  | leaveMeetupResponse401
  | leaveMeetupResponse404
  | leaveMeetupResponse422
) & {
  headers: Headers;
};

export type leaveMeetupResponse =
  leaveMeetupResponseSuccess | leaveMeetupResponseError;

export const getLeaveMeetupUrl = (questId: number) => {
  return `/api/quests/${questId}/rsvp`;
};

/**
 * Withdraw a meetup RSVP.
 * @summary Leave Meetup
 */
export const leaveMeetup = async (
  questId: number,
  options?: RequestInit,
): Promise<leaveMeetupResponse> => {
  const res = await fetch(getLeaveMeetupUrl(questId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: leaveMeetupResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as leaveMeetupResponse;
};

export const getLeaveMeetupMutationKey = () => ["leaveMeetup"] as const;

export const getLeaveMeetupMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveMeetup>>,
    TError,
    LeaveMeetupMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof leaveMeetup>>,
  TError,
  LeaveMeetupMutationVariables,
  TContext
> => {
  const mutationKey = getLeaveMeetupMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leaveMeetup>>,
    LeaveMeetupMutationVariables
  > = (props) => {
    const { questId } = props ?? {};

    return leaveMeetup(questId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LeaveMeetupMutationResult = NonNullable<
  Awaited<ReturnType<typeof leaveMeetup>>
>;

export type LeaveMeetupMutationError = ErrorResponse | HTTPValidationError;
export type LeaveMeetupMutationVariables = { questId: number };

/**
 * @summary Leave Meetup
 */
export const useLeaveMeetup = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leaveMeetup>>,
      TError,
      LeaveMeetupMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof leaveMeetup>>,
  TError,
  LeaveMeetupMutationVariables,
  TContext
> => {
  return useMutation(getLeaveMeetupMutationOptions(options), queryClient);
};
export type reportQuestResponse204 = {
  data: void;
  status: 204;
};

export type reportQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type reportQuestResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type reportQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type reportQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type reportQuestResponseSuccess = reportQuestResponse204 & {
  headers: Headers;
};
export type reportQuestResponseError = (
  | reportQuestResponse401
  | reportQuestResponse404
  | reportQuestResponse409
  | reportQuestResponse422
) & {
  headers: Headers;
};

export type reportQuestResponse =
  reportQuestResponseSuccess | reportQuestResponseError;

export const getReportQuestUrl = (questId: number) => {
  return `/api/quests/${questId}/report`;
};

/**
 * Report inappropriate quest content to the maintainers.
 * @summary Report Quest
 */
export const reportQuest = async (
  questId: number,
  reportRequest: ReportRequest,
  options?: RequestInit,
): Promise<reportQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getReportQuestUrl(questId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(reportRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: reportQuestResponse["data"] = body ? JSON.parse(body) : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as reportQuestResponse;
};

export const getReportQuestMutationKey = () => ["reportQuest"] as const;

export const getReportQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reportQuest>>,
    TError,
    ReportQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reportQuest>>,
  TError,
  ReportQuestMutationVariables,
  TContext
> => {
  const mutationKey = getReportQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reportQuest>>,
    ReportQuestMutationVariables
  > = (props) => {
    const { questId, data } = props ?? {};

    return reportQuest(questId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof reportQuest>>
>;
export type ReportQuestMutationBody = ReportRequest;
export type ReportQuestMutationError = ErrorResponse | HTTPValidationError;
export type ReportQuestMutationVariables = {
  questId: number;
  data: ReportRequest;
};

/**
 * @summary Report Quest
 */
export const useReportQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reportQuest>>,
      TError,
      ReportQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reportQuest>>,
  TError,
  ReportQuestMutationVariables,
  TContext
> => {
  return useMutation(getReportQuestMutationOptions(options), queryClient);
};
export type submitQuestResponse201 = {
  data: SubmissionOut;
  status: 201;
};

export type submitQuestResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type submitQuestResponse409 = {
  data: ErrorResponse;
  status: 409;
};

export type submitQuestResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type submitQuestResponseSuccess = submitQuestResponse201 & {
  headers: Headers;
};
export type submitQuestResponseError = (
  submitQuestResponse401 | submitQuestResponse409 | submitQuestResponse422
) & {
  headers: Headers;
};

export type submitQuestResponse =
  submitQuestResponseSuccess | submitQuestResponseError;

export const getSubmitQuestUrl = () => {
  return `/api/submissions`;
};

/**
 * Propose a new solo quest. A maintainer reviews it before it is published.
 * @summary Submit Quest
 */
export const submitQuest = async (
  questSubmission: QuestSubmission,
  options?: RequestInit,
): Promise<submitQuestResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getSubmitQuestUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(questSubmission),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitQuestResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as submitQuestResponse;
};

export const getSubmitQuestMutationKey = () => ["submitQuest"] as const;

export const getSubmitQuestMutationOptions = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitQuest>>,
    TError,
    SubmitQuestMutationVariables,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitQuest>>,
  TError,
  SubmitQuestMutationVariables,
  TContext
> => {
  const mutationKey = getSubmitQuestMutationKey();
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitQuest>>,
    SubmitQuestMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return submitQuest(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitQuestMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitQuest>>
>;
export type SubmitQuestMutationBody = QuestSubmission;
export type SubmitQuestMutationError = ErrorResponse | HTTPValidationError;
export type SubmitQuestMutationVariables = { data: QuestSubmission };

/**
 * @summary Submit Quest
 */
export const useSubmitQuest = <
  TError = ErrorResponse | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitQuest>>,
      TError,
      SubmitQuestMutationVariables,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitQuest>>,
  TError,
  SubmitQuestMutationVariables,
  TContext
> => {
  return useMutation(getSubmitQuestMutationOptions(options), queryClient);
};
export type listMySubmissionsResponse200 = {
  data: SubmissionOut[];
  status: 200;
};

export type listMySubmissionsResponse401 = {
  data: ErrorResponse;
  status: 401;
};

export type listMySubmissionsResponseSuccess = listMySubmissionsResponse200 & {
  headers: Headers;
};
export type listMySubmissionsResponseError = listMySubmissionsResponse401 & {
  headers: Headers;
};

export type listMySubmissionsResponse =
  listMySubmissionsResponseSuccess | listMySubmissionsResponseError;

export const getListMySubmissionsUrl = () => {
  return `/api/submissions/mine`;
};

/**
 * The current player's submitted quests and their review status.
 * @summary List My Submissions
 */
export const listMySubmissions = async (
  options?: RequestInit,
): Promise<listMySubmissionsResponse> => {
  const res = await fetch(getListMySubmissionsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMySubmissionsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listMySubmissionsResponse;
};

export const getListMySubmissionsQueryKey = () => {
  return [`/api/submissions/mine`] as const;
};

export const getListMySubmissionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMySubmissions>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listMySubmissions>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMySubmissionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listMySubmissions>>
  > = ({ signal }) => listMySubmissions({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMySubmissions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListMySubmissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMySubmissions>>
>;
export type ListMySubmissionsQueryError = ErrorResponse;

export function useListMySubmissions<
  TData = Awaited<ReturnType<typeof listMySubmissions>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMySubmissions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMySubmissions>>,
          TError,
          Awaited<ReturnType<typeof listMySubmissions>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMySubmissions<
  TData = Awaited<ReturnType<typeof listMySubmissions>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMySubmissions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMySubmissions>>,
          TError,
          Awaited<ReturnType<typeof listMySubmissions>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMySubmissions<
  TData = Awaited<ReturnType<typeof listMySubmissions>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMySubmissions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List My Submissions
 */

export function useListMySubmissions<
  TData = Awaited<ReturnType<typeof listMySubmissions>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listMySubmissions>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListMySubmissionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
