/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { UserRead } from "./hackathon.schemas";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getMeMeGetResponse200 = {
  data: UserRead;
  status: 200;
};

export type getMeMeGetResponseSuccess = getMeMeGetResponse200 & {
  headers: Headers;
};
export type getMeMeGetResponse = getMeMeGetResponseSuccess;

export const getGetMeMeGetUrl = () => {
  return `/api/me`;
};

/**
 * Return the logged-in user's profile and score.
 * @summary Get Me
 */
export const getMeMeGet = async (
  options?: RequestInit,
): Promise<getMeMeGetResponse> => {
  const res = await fetch(getGetMeMeGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeMeGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMeMeGetResponse;
};

export const getGetMeMeGetQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetMeMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeMeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeMeGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeMeGet>>> = ({
    signal,
  }) => getMeMeGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeMeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMeMeGet>>
>;
export type GetMeMeGetQueryError = unknown;

export function useGetMeMeGet<
  TData = Awaited<ReturnType<typeof getMeMeGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeMeGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMeMeGet<
  TData = Awaited<ReturnType<typeof getMeMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeMeGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMeMeGet<
  TData = Awaited<ReturnType<typeof getMeMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Me
 */

export function useGetMeMeGet<
  TData = Awaited<ReturnType<typeof getMeMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMeMeGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getLeaderboardLeaderboardGetResponse200 = {
  data: UserRead[];
  status: 200;
};

export type getLeaderboardLeaderboardGetResponseSuccess =
  getLeaderboardLeaderboardGetResponse200 & {
    headers: Headers;
  };
export type getLeaderboardLeaderboardGetResponse =
  getLeaderboardLeaderboardGetResponseSuccess;

export const getGetLeaderboardLeaderboardGetUrl = () => {
  return `/api/leaderboard`;
};

/**
 * List all users ordered by score, with username as a stable tiebreaker.
 * @summary Get Leaderboard
 */
export const getLeaderboardLeaderboardGet = async (
  options?: RequestInit,
): Promise<getLeaderboardLeaderboardGetResponse> => {
  const res = await fetch(getGetLeaderboardLeaderboardGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLeaderboardLeaderboardGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getLeaderboardLeaderboardGetResponse;
};

export const getGetLeaderboardLeaderboardGetQueryKey = () => {
  return [`/api/leaderboard`] as const;
};

export const getGetLeaderboardLeaderboardGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetLeaderboardLeaderboardGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>
  > = ({ signal }) => getLeaderboardLeaderboardGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeaderboardLeaderboardGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>
>;
export type GetLeaderboardLeaderboardGetQueryError = unknown;

export function useGetLeaderboardLeaderboardGet<
  TData = Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaderboardLeaderboardGet<
  TData = Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaderboardLeaderboardGet<
  TData = Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Leaderboard
 */

export function useGetLeaderboardLeaderboardGet<
  TData = Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaderboardLeaderboardGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeaderboardLeaderboardGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
